//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConexionBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class cat_sucursales
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cat_sucursales()
        {
            this.cat_configuracion_ticket_apartado = new HashSet<cat_configuracion_ticket_apartado>();
            this.cat_configuracion_ticket_venta = new HashSet<cat_configuracion_ticket_venta>();
            this.cat_gastos = new HashSet<cat_gastos>();
            this.cat_gastos1 = new HashSet<cat_gastos>();
            this.cat_lineas = new HashSet<cat_lineas>();
            this.cat_lineas1 = new HashSet<cat_lineas>();
            this.cat_productos = new HashSet<cat_productos>();
            this.cat_productos1 = new HashSet<cat_productos>();
            this.cat_productos_config_sucursal = new HashSet<cat_productos_config_sucursal>();
            this.cat_productos_existencias = new HashSet<cat_productos_existencias>();
            this.doc_inv_movimiento = new HashSet<doc_inv_movimiento>();
            this.doc_inv_movimiento1 = new HashSet<doc_inv_movimiento>();
            this.doc_inv_movimiento2 = new HashSet<doc_inv_movimiento>();
            this.doc_inv_movimiento3 = new HashSet<doc_inv_movimiento>();
            this.doc_inv_movimiento4 = new HashSet<doc_inv_movimiento>();
            this.doc_inv_movimiento5 = new HashSet<doc_inv_movimiento>();
            this.cat_usuarios = new HashSet<cat_usuarios>();
            this.doc_apartados = new HashSet<doc_apartados>();
            this.doc_gastos = new HashSet<doc_gastos>();
            this.doc_inv_carga_inicial = new HashSet<doc_inv_carga_inicial>();
            this.doc_promociones = new HashSet<doc_promociones>();
            this.doc_retiros = new HashSet<doc_retiros>();
            this.doc_productos_compra = new HashSet<doc_productos_compra>();
            this.doc_ventas = new HashSet<doc_ventas>();
            this.doc_pedidos_configuracion = new HashSet<doc_pedidos_configuracion>();
            this.cat_rest_mesas = new HashSet<cat_rest_mesas>();
            this.cat_rest_comandas = new HashSet<cat_rest_comandas>();
            this.doc_pedidos_orden = new HashSet<doc_pedidos_orden>();
            this.cat_impresoras = new HashSet<cat_impresoras>();
            this.doc_promociones_cm = new HashSet<doc_promociones_cm>();
            this.cat_usuarios_sucursales = new HashSet<cat_usuarios_sucursales>();
            this.doc_cargo_adicional_config = new HashSet<doc_cargo_adicional_config>();
            this.cat_clientes = new HashSet<cat_clientes>();
            this.doc_productos_minimo = new HashSet<doc_productos_minimo>();
            this.cat_basculas = new HashSet<cat_basculas>();
            this.doc_basculas_bitacora = new HashSet<doc_basculas_bitacora>();
            this.doc_produccion = new HashSet<doc_produccion>();
            this.sis_bitacora_general = new HashSet<sis_bitacora_general>();
            this.sis_bitacora_general1 = new HashSet<sis_bitacora_general>();
            this.doc_sucursales_productos_recepcion = new HashSet<doc_sucursales_productos_recepcion>();
            this.doc_declaracion_fondo_inicial = new HashSet<doc_declaracion_fondo_inicial>();
            this.doc_productos_sobrantes_registro = new HashSet<doc_productos_sobrantes_registro>();
            this.doc_produccion_solicitud = new HashSet<doc_produccion_solicitud>();
            this.doc_produccion_solicitud1 = new HashSet<doc_produccion_solicitud>();
            this.cat_sucursales_departamentos = new HashSet<cat_sucursales_departamentos>();
            this.cat_produccion_productos_sucursal = new HashSet<cat_produccion_productos_sucursal>();
            this.doc_inventario_registro = new HashSet<doc_inventario_registro>();
            this.cat_productos_principales = new HashSet<cat_productos_principales>();
            this.doc_cocimientos_grupos = new HashSet<doc_cocimientos_grupos>();
            this.doc_produccion_finalizada = new HashSet<doc_produccion_finalizada>();
            this.doc_aceptaciones_sucursal = new HashSet<doc_aceptaciones_sucursal>();
            this.doc_pedidos_orden1 = new HashSet<doc_pedidos_orden>();
            this.doc_inventario_captura = new HashSet<doc_inventario_captura>();
            this.doc_corte_caja_datos_entrada = new HashSet<doc_corte_caja_datos_entrada>();
            this.doc_precios_especiales = new HashSet<doc_precios_especiales>();
            this.sis_preferencias_sucursales = new HashSet<sis_preferencias_sucursales>();
            this.cat_sucursales_productos = new HashSet<cat_sucursales_productos>();
            this.doc_equipo_computo_bascula_registro = new HashSet<doc_equipo_computo_bascula_registro>();
            this.cat_equipos_computo = new HashSet<cat_equipos_computo>();
            this.cat_basculas_configuracion = new HashSet<cat_basculas_configuracion>();
        }
    
        public int Clave { get; set; }
        public Nullable<int> Empresa { get; set; }
        public string Calle { get; set; }
        public string Colonia { get; set; }
        public string NoExt { get; set; }
        public string NoInt { get; set; }
        public string Ciudad { get; set; }
        public string Estado { get; set; }
        public string Pais { get; set; }
        public string Telefono1 { get; set; }
        public string Telefono2 { get; set; }
        public string Email { get; set; }
        public Nullable<bool> Estatus { get; set; }
        public string NombreSucursal { get; set; }
        public string CP { get; set; }
        public string ServidorMailSMTP { get; set; }
        public string ServidorMailFrom { get; set; }
        public Nullable<short> ServidorMailPort { get; set; }
        public string ServidorMailPassword { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cat_configuracion_ticket_apartado> cat_configuracion_ticket_apartado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cat_configuracion_ticket_venta> cat_configuracion_ticket_venta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cat_gastos> cat_gastos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cat_gastos> cat_gastos1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cat_lineas> cat_lineas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cat_lineas> cat_lineas1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cat_productos> cat_productos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cat_productos> cat_productos1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cat_productos_config_sucursal> cat_productos_config_sucursal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cat_productos_existencias> cat_productos_existencias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<doc_inv_movimiento> doc_inv_movimiento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<doc_inv_movimiento> doc_inv_movimiento1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<doc_inv_movimiento> doc_inv_movimiento2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<doc_inv_movimiento> doc_inv_movimiento3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<doc_inv_movimiento> doc_inv_movimiento4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<doc_inv_movimiento> doc_inv_movimiento5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cat_usuarios> cat_usuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<doc_apartados> doc_apartados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<doc_gastos> doc_gastos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<doc_inv_carga_inicial> doc_inv_carga_inicial { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<doc_promociones> doc_promociones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<doc_retiros> doc_retiros { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<doc_productos_compra> doc_productos_compra { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<doc_ventas> doc_ventas { get; set; }
        public virtual cat_web_configuracion cat_web_configuracion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<doc_pedidos_configuracion> doc_pedidos_configuracion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cat_rest_mesas> cat_rest_mesas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cat_rest_comandas> cat_rest_comandas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<doc_pedidos_orden> doc_pedidos_orden { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cat_impresoras> cat_impresoras { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<doc_promociones_cm> doc_promociones_cm { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cat_usuarios_sucursales> cat_usuarios_sucursales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<doc_cargo_adicional_config> doc_cargo_adicional_config { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cat_clientes> cat_clientes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<doc_productos_minimo> doc_productos_minimo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cat_basculas> cat_basculas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<doc_basculas_bitacora> doc_basculas_bitacora { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<doc_produccion> doc_produccion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sis_bitacora_general> sis_bitacora_general { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sis_bitacora_general> sis_bitacora_general1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<doc_sucursales_productos_recepcion> doc_sucursales_productos_recepcion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<doc_declaracion_fondo_inicial> doc_declaracion_fondo_inicial { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<doc_productos_sobrantes_registro> doc_productos_sobrantes_registro { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<doc_produccion_solicitud> doc_produccion_solicitud { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<doc_produccion_solicitud> doc_produccion_solicitud1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cat_sucursales_departamentos> cat_sucursales_departamentos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cat_produccion_productos_sucursal> cat_produccion_productos_sucursal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<doc_inventario_registro> doc_inventario_registro { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cat_productos_principales> cat_productos_principales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<doc_cocimientos_grupos> doc_cocimientos_grupos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<doc_produccion_finalizada> doc_produccion_finalizada { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<doc_aceptaciones_sucursal> doc_aceptaciones_sucursal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<doc_pedidos_orden> doc_pedidos_orden1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<doc_inventario_captura> doc_inventario_captura { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<doc_corte_caja_datos_entrada> doc_corte_caja_datos_entrada { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<doc_precios_especiales> doc_precios_especiales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sis_preferencias_sucursales> sis_preferencias_sucursales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cat_sucursales_productos> cat_sucursales_productos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<doc_equipo_computo_bascula_registro> doc_equipo_computo_bascula_registro { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cat_equipos_computo> cat_equipos_computo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cat_basculas_configuracion> cat_basculas_configuracion { get; set; }
    }
}
