//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConexionBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class cat_rest_platillo_adicionales
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cat_rest_platillo_adicionales()
        {
            this.cat_rest_platillo_adicionales_sfam = new HashSet<cat_rest_platillo_adicionales_sfam>();
            this.doc_pedidos_orden_adicional = new HashSet<doc_pedidos_orden_adicional>();
        }
    
        public int Id { get; set; }
        public string Descripcion { get; set; }
        public bool MostrarSiempre { get; set; }
        public bool Activo { get; set; }
        public System.DateTime CreadoEl { get; set; }
        public int CreadoPor { get; set; }
    
        public virtual cat_usuarios cat_usuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cat_rest_platillo_adicionales_sfam> cat_rest_platillo_adicionales_sfam { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<doc_pedidos_orden_adicional> doc_pedidos_orden_adicional { get; set; }
    }
}
