//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConexionBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class cat_cajas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cat_cajas()
        {
            this.cat_gastos = new HashSet<cat_gastos>();
            this.cat_gastos1 = new HashSet<cat_gastos>();
            this.doc_apartados_pagos = new HashSet<doc_apartados_pagos>();
            this.doc_corte_caja = new HashSet<doc_corte_caja>();
            this.doc_gastos = new HashSet<doc_gastos>();
            this.doc_reimpresion_ticket = new HashSet<doc_reimpresion_ticket>();
            this.doc_retiros = new HashSet<doc_retiros>();
            this.doc_ventas = new HashSet<doc_ventas>();
            this.cat_cajas_impresora = new HashSet<cat_cajas_impresora>();
            this.cat_usuarios = new HashSet<cat_usuarios>();
            this.doc_pedidos_orden = new HashSet<doc_pedidos_orden>();
            this.doc_declaracion_fondo_inicial = new HashSet<doc_declaracion_fondo_inicial>();
            this.doc_sesiones_punto_venta = new HashSet<doc_sesiones_punto_venta>();
        }
    
        public int Clave { get; set; }
        public string Descripcion { get; set; }
        public string Ubicacion { get; set; }
        public Nullable<bool> Estatus { get; set; }
        public Nullable<int> Empresa { get; set; }
        public Nullable<int> Sucursal { get; set; }
        public Nullable<short> TipoCajaId { get; set; }
    
        public virtual cat_empresas cat_empresas { get; set; }
        public virtual cat_empresas cat_empresas1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cat_gastos> cat_gastos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cat_gastos> cat_gastos1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<doc_apartados_pagos> doc_apartados_pagos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<doc_corte_caja> doc_corte_caja { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<doc_gastos> doc_gastos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<doc_reimpresion_ticket> doc_reimpresion_ticket { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<doc_retiros> doc_retiros { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<doc_ventas> doc_ventas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cat_cajas_impresora> cat_cajas_impresora { get; set; }
        public virtual cat_tipos_cajas cat_tipos_cajas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cat_usuarios> cat_usuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<doc_pedidos_orden> doc_pedidos_orden { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<doc_declaracion_fondo_inicial> doc_declaracion_fondo_inicial { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<doc_sesiones_punto_venta> doc_sesiones_punto_venta { get; set; }
    }
}
