//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConexionBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class cat_sucursales_departamentos
    {
        public int SucursalId { get; set; }
        public int DepartamentoId { get; set; }
        public System.DateTime CreadoEl { get; set; }
        public int CreadoPor { get; set; }
    
        public virtual cat_departamentos cat_departamentos { get; set; }
        public virtual cat_sucursales cat_sucursales { get; set; }
    }
}
