//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConexionBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class cat_productos_imagenes
    {
        public int ProductoImageId { get; set; }
        public int ProductoId { get; set; }
        public string FileName { get; set; }
        public System.DateTime CreadoEl { get; set; }
        public byte[] FileByte { get; set; }
        public Nullable<bool> Principal { get; set; }
        public Nullable<bool> Miniatura { get; set; }
    
        public virtual cat_productos cat_productos { get; set; }
    }
}
