//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConexionBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class cat_configuracion
    {
        public int ConfiguradorId { get; set; }
        public Nullable<bool> UnaFormaPago { get; set; }
        public Nullable<bool> MasUnaFormaPago { get; set; }
        public Nullable<bool> CosteoUEPS { get; set; }
        public Nullable<bool> CosteoPEPS { get; set; }
        public Nullable<bool> CosteoPromedio { get; set; }
        public Nullable<bool> AfectarInventarioLinea { get; set; }
        public Nullable<bool> AfectarInventarioManual { get; set; }
        public Nullable<bool> AfectarInventarioCorte { get; set; }
        public Nullable<bool> EnlazarPuntoVentaInventario { get; set; }
        public Nullable<bool> CajeroIncluirDetalleVenta { get; set; }
        public Nullable<bool> CajeroReqClaveSupervisor { get; set; }
        public Nullable<bool> SuperIncluirDetalleVenta { get; set; }
        public Nullable<bool> SuperIncluirVentaTel { get; set; }
        public Nullable<bool> SuperIncluirDetGastos { get; set; }
        public string SuperEmail1 { get; set; }
        public string SuperEmail2 { get; set; }
        public string SuperEmail3 { get; set; }
        public string SuperEmail4 { get; set; }
        public Nullable<decimal> RetiroMontoEfec { get; set; }
        public Nullable<bool> RetiroLectura { get; set; }
        public Nullable<bool> RetiroEscritura { get; set; }
        public string NombreImpresora { get; set; }
        public string HardwareCaracterCajon { get; set; }
        public Nullable<decimal> EmpleadoPorcDescuento { get; set; }
        public Nullable<bool> EmpleadoGlobal { get; set; }
        public Nullable<bool> EmpleadoIndividual { get; set; }
        public Nullable<decimal> MontoImpresionTicket { get; set; }
        public Nullable<decimal> ApartadoAnticipo1 { get; set; }
        public Nullable<decimal> ApartadoAnticipoHasta1 { get; set; }
        public Nullable<decimal> ApartadoAnticipo2 { get; set; }
        public Nullable<decimal> ApatadoAnticipoEnAdelante2 { get; set; }
        public Nullable<decimal> PorcentajeUtilidadProd { get; set; }
        public Nullable<bool> DesgloceMontoTicket { get; set; }
        public Nullable<bool> RetiroReqClaveSup { get; set; }
        public Nullable<bool> CajDeclaracionFondoCorte { get; set; }
        public Nullable<bool> SupDeclaracionFondoCorte { get; set; }
        public Nullable<bool> vistaPreviaImpresion { get; set; }
        public Nullable<bool> CajeroCorteDetGasto { get; set; }
        public Nullable<bool> SupCorteDetGasto { get; set; }
        public Nullable<bool> CajeroCorteCancelaciones { get; set; }
        public Nullable<bool> SupCorteCancelaciones { get; set; }
        public Nullable<byte> DevDiasVale { get; set; }
        public Nullable<byte> DevDiasGarantia { get; set; }
        public Nullable<byte> DevHorasGarantia { get; set; }
        public Nullable<byte> ApartadoDiasLiq { get; set; }
        public Nullable<byte> ApartadoDiasProrroga { get; set; }
        public Nullable<bool> ReqClaveSupReimpresionTicketPV { get; set; }
        public Nullable<bool> ReqClaveSupCancelaTicketPV { get; set; }
        public Nullable<bool> ReqClaveSupGastosPV { get; set; }
        public Nullable<bool> ReqClaveSupDevolucionPV { get; set; }
        public Nullable<bool> ReqClaveSupApartadoPV { get; set; }
        public Nullable<bool> ReqClaveSupExistenciaPV { get; set; }
        public string SerieTicketVenta { get; set; }
        public string SerieTicketApartado { get; set; }
        public Nullable<bool> CorteCajaIncluirExistencia { get; set; }
        public Nullable<bool> ImprimirTicketMediaCarta { get; set; }
        public string Giro { get; set; }
        public Nullable<bool> SolicitarComanda { get; set; }
        public Nullable<bool> TieneRec { get; set; }
        public Nullable<decimal> PorcRec { get; set; }
        public Nullable<decimal> MontoRecargoDiario { get; set; }
        public Nullable<decimal> PedidoAnticipoPorc { get; set; }
        public Nullable<int> PedidoPoliticaId { get; set; }
    
        public virtual cat_politicas cat_politicas { get; set; }
    }
}
