//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConexionBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class cat_basculas_configuracion
    {
        public int EquipoComputoId { get; set; }
        public int BasculaId { get; set; }
        public string PortName { get; set; }
        public int BaudRate { get; set; }
        public int ReadBufferSize { get; set; }
        public int WriteBufferSize { get; set; }
        public System.DateTime CreadoEl { get; set; }
        public int CreadoPor { get; set; }
        public Nullable<decimal> PesoDefault { get; set; }
        public Nullable<int> SucursalId { get; set; }
    
        public virtual cat_basculas cat_basculas { get; set; }
        public virtual cat_equipos_computo cat_equipos_computo { get; set; }
        public virtual cat_sucursales cat_sucursales { get; set; }
    }
}
