//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConexionBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class cat_rest_platillo_adicionales_sfam
    {
        public int PlatilloAdicionalId { get; set; }
        public int SubfamiliaId { get; set; }
        public System.DateTime CreadoEl { get; set; }
    
        public virtual cat_rest_platillo_adicionales cat_rest_platillo_adicionales { get; set; }
        public virtual cat_subfamilias cat_subfamilias { get; set; }
    }
}
