//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConexionBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class cat_clientes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cat_clientes()
        {
            this.doc_apartados = new HashSet<doc_apartados>();
            this.doc_ventas = new HashSet<doc_ventas>();
            this.cat_clientes_automovil = new HashSet<cat_clientes_automovil>();
            this.doc_pedidos_orden = new HashSet<doc_pedidos_orden>();
            this.doc_web_carrito = new HashSet<doc_web_carrito>();
            this.cat_clientes_direcciones = new HashSet<cat_clientes_direcciones>();
            this.doc_pedidos_orden_programacion = new HashSet<doc_pedidos_orden_programacion>();
            this.doc_cargos = new HashSet<doc_cargos>();
            this.doc_clientes_productos_precios = new HashSet<doc_clientes_productos_precios>();
            this.doc_pagos = new HashSet<doc_pagos>();
        }
    
        public int ClienteId { get; set; }
        public string Nombre { get; set; }
        public string RFC { get; set; }
        public string Calle { get; set; }
        public string NumeroExt { get; set; }
        public string NumeroInt { get; set; }
        public string Colonia { get; set; }
        public string CodigoPostal { get; set; }
        public Nullable<int> EstadoId { get; set; }
        public Nullable<int> MunicipioId { get; set; }
        public Nullable<short> PaisId { get; set; }
        public string Telefono { get; set; }
        public string Telefono2 { get; set; }
        public Nullable<byte> TipoClienteId { get; set; }
        public Nullable<short> DiasCredito { get; set; }
        public Nullable<decimal> LimiteCredito { get; set; }
        public Nullable<int> AntecedenteId { get; set; }
        public Nullable<decimal> CreditoDisponible { get; set; }
        public Nullable<decimal> SaldoGlobal { get; set; }
        public Nullable<bool> Activo { get; set; }
        public Nullable<bool> ClienteEspecial { get; set; }
        public Nullable<bool> ClienteGral { get; set; }
        public Nullable<byte> PrecioId { get; set; }
        public Nullable<int> GiroId { get; set; }
        public Nullable<System.Guid> UUID { get; set; }
        public string KeyClient { get; set; }
        public Nullable<int> GiroNegocioId { get; set; }
        public string ApellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }
        public Nullable<int> EmpleadoId { get; set; }
        public string Clave { get; set; }
        public Nullable<int> SucursalBaseId { get; set; }
        public string pass { get; set; }
    
        public virtual cat_antecedentes cat_antecedentes { get; set; }
        public virtual cat_estados cat_estados { get; set; }
        public virtual cat_giros_neg cat_giros_neg { get; set; }
        public virtual cat_municipios cat_municipios { get; set; }
        public virtual cat_paises cat_paises { get; set; }
        public virtual cat_precios cat_precios { get; set; }
        public virtual cat_tipos_cliente cat_tipos_cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<doc_apartados> doc_apartados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<doc_ventas> doc_ventas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cat_clientes_automovil> cat_clientes_automovil { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<doc_pedidos_orden> doc_pedidos_orden { get; set; }
        public virtual rh_empleados rh_empleados { get; set; }
        public virtual cat_clientes_contacto cat_clientes_contacto { get; set; }
        public virtual cat_sucursales cat_sucursales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<doc_web_carrito> doc_web_carrito { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cat_clientes_direcciones> cat_clientes_direcciones { get; set; }
        public virtual cat_clientes_web cat_clientes_web { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<doc_pedidos_orden_programacion> doc_pedidos_orden_programacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<doc_cargos> doc_cargos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<doc_clientes_productos_precios> doc_clientes_productos_precios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<doc_pagos> doc_pagos { get; set; }
    }
}
