//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConexionBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class cat_clientes_direcciones
    {
        public int ClienteDireccionId { get; set; }
        public int ClienteId { get; set; }
        public byte TipoDireccionId { get; set; }
        public string Calle { get; set; }
        public string NumeroInterior { get; set; }
        public string NumeroExterior { get; set; }
        public string Colonia { get; set; }
        public string Ciudad { get; set; }
        public Nullable<int> EstadoId { get; set; }
        public Nullable<int> PaisId { get; set; }
        public string CodigoPostal { get; set; }
        public Nullable<System.DateTime> CreadoEl { get; set; }
    
        public virtual cat_clientes cat_clientes { get; set; }
        public virtual cat_estados cat_estados { get; set; }
    }
}
