//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConexionBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class cat_configuracion_ticket_apartado
    {
        public int ConfiguracionTicketVentaId { get; set; }
        public int SucursalId { get; set; }
        public string TextoCabecera1 { get; set; }
        public string TextoCabecera2 { get; set; }
        public string TextoPie { get; set; }
        public System.DateTime CreadoEl { get; set; }
        public int CreadoPor { get; set; }
        public string Serie { get; set; }
    
        public virtual cat_sucursales cat_sucursales { get; set; }
    }
}
