//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConexionBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class cat_productos_agrupados
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cat_productos_agrupados()
        {
            this.cat_productos_agrupados_detalle = new HashSet<cat_productos_agrupados_detalle>();
        }
    
        public int ProductoAgrupadoId { get; set; }
        public string Descripcion { get; set; }
        public string DescripcionCorta { get; set; }
        public System.DateTime CreadoEl { get; set; }
        public string Especificaciones { get; set; }
        public int ProductoId { get; set; }
        public Nullable<byte> Rating { get; set; }
        public Nullable<bool> Liquidacion { get; set; }
    
        public virtual cat_productos cat_productos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cat_productos_agrupados_detalle> cat_productos_agrupados_detalle { get; set; }
    }
}
