//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConexionBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class cat_empresas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cat_empresas()
        {
            this.cat_almacenes = new HashSet<cat_almacenes>();
            this.cat_almacenes1 = new HashSet<cat_almacenes>();
            this.cat_almacenes2 = new HashSet<cat_almacenes>();
            this.cat_almacenes3 = new HashSet<cat_almacenes>();
            this.cat_anaqueles = new HashSet<cat_anaqueles>();
            this.cat_anaqueles1 = new HashSet<cat_anaqueles>();
            this.cat_anaqueles2 = new HashSet<cat_anaqueles>();
            this.cat_anaqueles3 = new HashSet<cat_anaqueles>();
            this.cat_andenes = new HashSet<cat_andenes>();
            this.cat_andenes1 = new HashSet<cat_andenes>();
            this.cat_andenes2 = new HashSet<cat_andenes>();
            this.cat_andenes3 = new HashSet<cat_andenes>();
            this.cat_cajas = new HashSet<cat_cajas>();
            this.cat_cajas1 = new HashSet<cat_cajas>();
            this.cat_centro_costos = new HashSet<cat_centro_costos>();
            this.cat_centro_costos1 = new HashSet<cat_centro_costos>();
            this.cat_centro_costos2 = new HashSet<cat_centro_costos>();
            this.cat_centro_costos3 = new HashSet<cat_centro_costos>();
            this.cat_clases_sat = new HashSet<cat_clases_sat>();
            this.cat_clases_sat1 = new HashSet<cat_clases_sat>();
            this.cat_clases_sat2 = new HashSet<cat_clases_sat>();
            this.cat_clases_sat3 = new HashSet<cat_clases_sat>();
            this.cat_denominaciones = new HashSet<cat_denominaciones>();
            this.cat_denominaciones1 = new HashSet<cat_denominaciones>();
            this.cat_denominaciones2 = new HashSet<cat_denominaciones>();
            this.cat_denominaciones3 = new HashSet<cat_denominaciones>();
            this.cat_denominaciones4 = new HashSet<cat_denominaciones>();
            this.cat_denominaciones5 = new HashSet<cat_denominaciones>();
            this.cat_denominaciones6 = new HashSet<cat_denominaciones>();
            this.cat_denominaciones7 = new HashSet<cat_denominaciones>();
            this.cat_denominaciones8 = new HashSet<cat_denominaciones>();
            this.cat_denominaciones9 = new HashSet<cat_denominaciones>();
            this.cat_denominaciones10 = new HashSet<cat_denominaciones>();
            this.cat_denominaciones11 = new HashSet<cat_denominaciones>();
            this.cat_denominaciones12 = new HashSet<cat_denominaciones>();
            this.cat_denominaciones13 = new HashSet<cat_denominaciones>();
            this.cat_denominaciones14 = new HashSet<cat_denominaciones>();
            this.cat_denominaciones15 = new HashSet<cat_denominaciones>();
            this.cat_denominaciones16 = new HashSet<cat_denominaciones>();
            this.cat_denominaciones17 = new HashSet<cat_denominaciones>();
            this.cat_denominaciones18 = new HashSet<cat_denominaciones>();
            this.cat_denominaciones19 = new HashSet<cat_denominaciones>();
            this.cat_denominaciones20 = new HashSet<cat_denominaciones>();
            this.cat_denominaciones21 = new HashSet<cat_denominaciones>();
            this.cat_denominaciones22 = new HashSet<cat_denominaciones>();
            this.cat_denominaciones23 = new HashSet<cat_denominaciones>();
            this.cat_divisiones_sat = new HashSet<cat_divisiones_sat>();
            this.cat_divisiones_sat1 = new HashSet<cat_divisiones_sat>();
            this.cat_divisiones_sat2 = new HashSet<cat_divisiones_sat>();
            this.cat_divisiones_sat3 = new HashSet<cat_divisiones_sat>();
            this.cat_familias = new HashSet<cat_familias>();
            this.cat_familias1 = new HashSet<cat_familias>();
            this.cat_familias2 = new HashSet<cat_familias>();
            this.cat_familias3 = new HashSet<cat_familias>();
            this.cat_gastos = new HashSet<cat_gastos>();
            this.cat_gastos1 = new HashSet<cat_gastos>();
            this.cat_giros_neg = new HashSet<cat_giros_neg>();
            this.cat_giros_neg1 = new HashSet<cat_giros_neg>();
            this.cat_giros_neg2 = new HashSet<cat_giros_neg>();
            this.cat_giros_neg3 = new HashSet<cat_giros_neg>();
            this.cat_grupos_sat = new HashSet<cat_grupos_sat>();
            this.cat_grupos_sat1 = new HashSet<cat_grupos_sat>();
            this.cat_grupos_sat2 = new HashSet<cat_grupos_sat>();
            this.cat_grupos_sat3 = new HashSet<cat_grupos_sat>();
            this.cat_lineas = new HashSet<cat_lineas>();
            this.cat_lineas1 = new HashSet<cat_lineas>();
            this.cat_lotes = new HashSet<cat_lotes>();
            this.cat_lotes1 = new HashSet<cat_lotes>();
            this.cat_lotes2 = new HashSet<cat_lotes>();
            this.cat_lotes3 = new HashSet<cat_lotes>();
            this.cat_marcas = new HashSet<cat_marcas>();
            this.cat_marcas1 = new HashSet<cat_marcas>();
            this.cat_marcas2 = new HashSet<cat_marcas>();
            this.cat_marcas3 = new HashSet<cat_marcas>();
            this.cat_monedas = new HashSet<cat_monedas>();
            this.cat_monedas1 = new HashSet<cat_monedas>();
            this.cat_monedas2 = new HashSet<cat_monedas>();
            this.cat_monedas3 = new HashSet<cat_monedas>();
            this.cat_productos = new HashSet<cat_productos>();
            this.cat_productos1 = new HashSet<cat_productos>();
            this.cat_rubros = new HashSet<cat_rubros>();
            this.cat_rubros1 = new HashSet<cat_rubros>();
            this.cat_rubros2 = new HashSet<cat_rubros>();
            this.cat_rubros3 = new HashSet<cat_rubros>();
            this.cat_subclases_sat = new HashSet<cat_subclases_sat>();
            this.cat_subclases_sat1 = new HashSet<cat_subclases_sat>();
            this.cat_subclases_sat2 = new HashSet<cat_subclases_sat>();
            this.cat_subclases_sat3 = new HashSet<cat_subclases_sat>();
            this.cat_subfamilias = new HashSet<cat_subfamilias>();
            this.cat_subfamilias1 = new HashSet<cat_subfamilias>();
            this.cat_subfamilias2 = new HashSet<cat_subfamilias>();
            this.cat_subfamilias3 = new HashSet<cat_subfamilias>();
            this.cat_unidadesmed = new HashSet<cat_unidadesmed>();
            this.cat_unidadesmed1 = new HashSet<cat_unidadesmed>();
            this.cat_unidadesmed2 = new HashSet<cat_unidadesmed>();
            this.cat_unidadesmed3 = new HashSet<cat_unidadesmed>();
            this.rh_departamentos = new HashSet<rh_departamentos>();
            this.rh_departamentos1 = new HashSet<rh_departamentos>();
            this.rh_departamentos2 = new HashSet<rh_departamentos>();
            this.rh_departamentos3 = new HashSet<rh_departamentos>();
            this.rh_empleados = new HashSet<rh_empleados>();
            this.rh_empleados1 = new HashSet<rh_empleados>();
            this.rh_empleados2 = new HashSet<rh_empleados>();
            this.rh_empleados3 = new HashSet<rh_empleados>();
            this.rh_estatus_empleados = new HashSet<rh_estatus_empleados>();
            this.rh_estatus_empleados1 = new HashSet<rh_estatus_empleados>();
            this.rh_estatus_empleados2 = new HashSet<rh_estatus_empleados>();
            this.rh_estatus_empleados3 = new HashSet<rh_estatus_empleados>();
            this.rh_formaspagonom = new HashSet<rh_formaspagonom>();
            this.rh_formaspagonom1 = new HashSet<rh_formaspagonom>();
            this.rh_formaspagonom2 = new HashSet<rh_formaspagonom>();
            this.rh_formaspagonom3 = new HashSet<rh_formaspagonom>();
            this.rh_puestos = new HashSet<rh_puestos>();
            this.rh_puestos1 = new HashSet<rh_puestos>();
            this.rh_puestos2 = new HashSet<rh_puestos>();
            this.rh_puestos3 = new HashSet<rh_puestos>();
            this.rh_tipos_contrato = new HashSet<rh_tipos_contrato>();
            this.rh_tipos_contrato1 = new HashSet<rh_tipos_contrato>();
            this.rh_tipos_contrato2 = new HashSet<rh_tipos_contrato>();
            this.rh_tipos_contrato3 = new HashSet<rh_tipos_contrato>();
            this.doc_promociones = new HashSet<doc_promociones>();
            this.cat_basculas = new HashSet<cat_basculas>();
        }
    
        public int Clave { get; set; }
        public string Nombre { get; set; }
        public string NombreComercial { get; set; }
        public string RegimenFiscal { get; set; }
        public string RFC { get; set; }
        public string Calle { get; set; }
        public string Colonia { get; set; }
        public string NoExt { get; set; }
        public string NoInt { get; set; }
        public string CP { get; set; }
        public string Ciudad { get; set; }
        public string Estado { get; set; }
        public string Pais { get; set; }
        public string Telefono1 { get; set; }
        public string Telefono2 { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> FechaAlta { get; set; }
        public Nullable<bool> Estatus { get; set; }
        public byte[] Logo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cat_almacenes> cat_almacenes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cat_almacenes> cat_almacenes1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cat_almacenes> cat_almacenes2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cat_almacenes> cat_almacenes3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cat_anaqueles> cat_anaqueles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cat_anaqueles> cat_anaqueles1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cat_anaqueles> cat_anaqueles2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cat_anaqueles> cat_anaqueles3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cat_andenes> cat_andenes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cat_andenes> cat_andenes1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cat_andenes> cat_andenes2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cat_andenes> cat_andenes3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cat_cajas> cat_cajas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cat_cajas> cat_cajas1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cat_centro_costos> cat_centro_costos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cat_centro_costos> cat_centro_costos1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cat_centro_costos> cat_centro_costos2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cat_centro_costos> cat_centro_costos3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cat_clases_sat> cat_clases_sat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cat_clases_sat> cat_clases_sat1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cat_clases_sat> cat_clases_sat2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cat_clases_sat> cat_clases_sat3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cat_denominaciones> cat_denominaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cat_denominaciones> cat_denominaciones1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cat_denominaciones> cat_denominaciones2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cat_denominaciones> cat_denominaciones3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cat_denominaciones> cat_denominaciones4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cat_denominaciones> cat_denominaciones5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cat_denominaciones> cat_denominaciones6 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cat_denominaciones> cat_denominaciones7 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cat_denominaciones> cat_denominaciones8 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cat_denominaciones> cat_denominaciones9 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cat_denominaciones> cat_denominaciones10 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cat_denominaciones> cat_denominaciones11 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cat_denominaciones> cat_denominaciones12 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cat_denominaciones> cat_denominaciones13 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cat_denominaciones> cat_denominaciones14 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cat_denominaciones> cat_denominaciones15 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cat_denominaciones> cat_denominaciones16 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cat_denominaciones> cat_denominaciones17 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cat_denominaciones> cat_denominaciones18 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cat_denominaciones> cat_denominaciones19 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cat_denominaciones> cat_denominaciones20 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cat_denominaciones> cat_denominaciones21 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cat_denominaciones> cat_denominaciones22 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cat_denominaciones> cat_denominaciones23 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cat_divisiones_sat> cat_divisiones_sat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cat_divisiones_sat> cat_divisiones_sat1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cat_divisiones_sat> cat_divisiones_sat2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cat_divisiones_sat> cat_divisiones_sat3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cat_familias> cat_familias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cat_familias> cat_familias1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cat_familias> cat_familias2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cat_familias> cat_familias3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cat_gastos> cat_gastos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cat_gastos> cat_gastos1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cat_giros_neg> cat_giros_neg { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cat_giros_neg> cat_giros_neg1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cat_giros_neg> cat_giros_neg2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cat_giros_neg> cat_giros_neg3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cat_grupos_sat> cat_grupos_sat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cat_grupos_sat> cat_grupos_sat1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cat_grupos_sat> cat_grupos_sat2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cat_grupos_sat> cat_grupos_sat3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cat_lineas> cat_lineas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cat_lineas> cat_lineas1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cat_lotes> cat_lotes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cat_lotes> cat_lotes1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cat_lotes> cat_lotes2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cat_lotes> cat_lotes3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cat_marcas> cat_marcas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cat_marcas> cat_marcas1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cat_marcas> cat_marcas2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cat_marcas> cat_marcas3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cat_monedas> cat_monedas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cat_monedas> cat_monedas1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cat_monedas> cat_monedas2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cat_monedas> cat_monedas3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cat_productos> cat_productos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cat_productos> cat_productos1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cat_rubros> cat_rubros { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cat_rubros> cat_rubros1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cat_rubros> cat_rubros2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cat_rubros> cat_rubros3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cat_subclases_sat> cat_subclases_sat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cat_subclases_sat> cat_subclases_sat1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cat_subclases_sat> cat_subclases_sat2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cat_subclases_sat> cat_subclases_sat3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cat_subfamilias> cat_subfamilias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cat_subfamilias> cat_subfamilias1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cat_subfamilias> cat_subfamilias2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cat_subfamilias> cat_subfamilias3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cat_unidadesmed> cat_unidadesmed { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cat_unidadesmed> cat_unidadesmed1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cat_unidadesmed> cat_unidadesmed2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cat_unidadesmed> cat_unidadesmed3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rh_departamentos> rh_departamentos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rh_departamentos> rh_departamentos1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rh_departamentos> rh_departamentos2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rh_departamentos> rh_departamentos3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rh_empleados> rh_empleados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rh_empleados> rh_empleados1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rh_empleados> rh_empleados2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rh_empleados> rh_empleados3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rh_estatus_empleados> rh_estatus_empleados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rh_estatus_empleados> rh_estatus_empleados1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rh_estatus_empleados> rh_estatus_empleados2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rh_estatus_empleados> rh_estatus_empleados3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rh_formaspagonom> rh_formaspagonom { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rh_formaspagonom> rh_formaspagonom1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rh_formaspagonom> rh_formaspagonom2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rh_formaspagonom> rh_formaspagonom3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rh_puestos> rh_puestos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rh_puestos> rh_puestos1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rh_puestos> rh_puestos2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rh_puestos> rh_puestos3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rh_tipos_contrato> rh_tipos_contrato { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rh_tipos_contrato> rh_tipos_contrato1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rh_tipos_contrato> rh_tipos_contrato2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rh_tipos_contrato> rh_tipos_contrato3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<doc_promociones> doc_promociones { get; set; }
        public virtual cat_empresas_config_inventario cat_empresas_config_inventario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cat_basculas> cat_basculas { get; set; }
        public virtual sis_cuenta sis_cuenta { get; set; }
    }
}
