//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConexionBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class cat_cargos_adicionales
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cat_cargos_adicionales()
        {
            this.doc_cargo_adicional_config = new HashSet<doc_cargo_adicional_config>();
            this.doc_ventas_detalle = new HashSet<doc_ventas_detalle>();
            this.doc_pedidos_orden_cargos = new HashSet<doc_pedidos_orden_cargos>();
        }
    
        public short CargoAdicionalId { get; set; }
        public string Descripcion { get; set; }
        public System.DateTime CreadoEl { get; set; }
        public Nullable<byte> CargoTipoId { get; set; }
    
        public virtual cat_cargos_tipos cat_cargos_tipos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<doc_cargo_adicional_config> doc_cargo_adicional_config { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<doc_ventas_detalle> doc_ventas_detalle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<doc_pedidos_orden_cargos> doc_pedidos_orden_cargos { get; set; }
    }
}
