//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConexionBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class cat_denominaciones
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cat_denominaciones()
        {
            this.doc_corte_caja_denominaciones = new HashSet<doc_corte_caja_denominaciones>();
            this.doc_declaracion_fondo_inicial_detalle = new HashSet<doc_declaracion_fondo_inicial_detalle>();
            this.doc_retiros_denominaciones = new HashSet<doc_retiros_denominaciones>();
        }
    
        public int Clave { get; set; }
        public string Descripcion { get; set; }
        public Nullable<decimal> Valor { get; set; }
        public Nullable<int> Orden { get; set; }
        public Nullable<bool> Estatus { get; set; }
        public Nullable<int> Empresa { get; set; }
        public Nullable<int> Sucursal { get; set; }
    
        public virtual cat_empresas cat_empresas { get; set; }
        public virtual cat_empresas cat_empresas1 { get; set; }
        public virtual cat_empresas cat_empresas2 { get; set; }
        public virtual cat_empresas cat_empresas3 { get; set; }
        public virtual cat_empresas cat_empresas4 { get; set; }
        public virtual cat_empresas cat_empresas5 { get; set; }
        public virtual cat_empresas cat_empresas6 { get; set; }
        public virtual cat_empresas cat_empresas7 { get; set; }
        public virtual cat_empresas cat_empresas8 { get; set; }
        public virtual cat_empresas cat_empresas9 { get; set; }
        public virtual cat_empresas cat_empresas10 { get; set; }
        public virtual cat_empresas cat_empresas11 { get; set; }
        public virtual cat_empresas cat_empresas12 { get; set; }
        public virtual cat_empresas cat_empresas13 { get; set; }
        public virtual cat_empresas cat_empresas14 { get; set; }
        public virtual cat_empresas cat_empresas15 { get; set; }
        public virtual cat_empresas cat_empresas16 { get; set; }
        public virtual cat_empresas cat_empresas17 { get; set; }
        public virtual cat_empresas cat_empresas18 { get; set; }
        public virtual cat_empresas cat_empresas19 { get; set; }
        public virtual cat_empresas cat_empresas20 { get; set; }
        public virtual cat_empresas cat_empresas21 { get; set; }
        public virtual cat_empresas cat_empresas22 { get; set; }
        public virtual cat_empresas cat_empresas23 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<doc_corte_caja_denominaciones> doc_corte_caja_denominaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<doc_declaracion_fondo_inicial_detalle> doc_declaracion_fondo_inicial_detalle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<doc_retiros_denominaciones> doc_retiros_denominaciones { get; set; }
    }
}
