//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConexionBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class cat_productos_imagenes
    {
        public int ProductoImageId { get; set; }
        public int ProductoId { get; set; }
        public string FileName { get; set; }
        public System.DateTime CreadoEl { get; set; }
        public byte[] FileByte { get; set; }
        public Nullable<bool> Principal { get; set; }
        public Nullable<bool> Miniatura { get; set; }
    
        public virtual cat_productos cat_productos { get; set; }
    }
}
