//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConexionBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class cat_configuracion_ticket_venta
    {
        public int ConfiguracionTicketVentaId { get; set; }
        public int SucursalId { get; set; }
        public string TextoCabecera1 { get; set; }
        public string TextoCabecera2 { get; set; }
        public string TextoPie { get; set; }
        public System.DateTime CreadoEl { get; set; }
        public int CreadoPor { get; set; }
        public string Serie { get; set; }
    
        public virtual cat_sucursales cat_sucursales { get; set; }
    }
}
