//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConexionBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class cat_productos_cambio_precio
    {
        public int Id { get; set; }
        public int ProductoId { get; set; }
        public byte PrecioId { get; set; }
        public decimal PrecioAnterior { get; set; }
        public decimal PrecioNuevo { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public Nullable<int> UsuarioRegistroId { get; set; }
    
        public virtual cat_productos cat_productos { get; set; }
        public virtual cat_usuarios cat_usuarios { get; set; }
    }
}
