//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConexionBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class cat_familias
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cat_familias()
        {
            this.cat_productos = new HashSet<cat_productos>();
            this.cat_productos1 = new HashSet<cat_productos>();
            this.cat_subfamilias = new HashSet<cat_subfamilias>();
            this.cat_subfamilias1 = new HashSet<cat_subfamilias>();
            this.doc_promociones_detalle = new HashSet<doc_promociones_detalle>();
            this.doc_promociones_excepcion = new HashSet<doc_promociones_excepcion>();
        }
    
        public int Clave { get; set; }
        public string Descripcion { get; set; }
        public Nullable<bool> Estatus { get; set; }
        public Nullable<int> Empresa { get; set; }
        public Nullable<int> Sucursal { get; set; }
        public Nullable<int> ProductoPortadaId { get; set; }
        public Nullable<short> Orden { get; set; }
    
        public virtual cat_empresas cat_empresas { get; set; }
        public virtual cat_empresas cat_empresas1 { get; set; }
        public virtual cat_empresas cat_empresas2 { get; set; }
        public virtual cat_empresas cat_empresas3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cat_productos> cat_productos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cat_productos> cat_productos1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cat_subfamilias> cat_subfamilias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cat_subfamilias> cat_subfamilias1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<doc_promociones_detalle> doc_promociones_detalle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<doc_promociones_excepcion> doc_promociones_excepcion { get; set; }
        public virtual cat_productos cat_productos2 { get; set; }
    }
}
