//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConexionBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class cat_tipos_movimiento_inventario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cat_tipos_movimiento_inventario()
        {
            this.cat_tipos_movimiento_inventario1 = new HashSet<cat_tipos_movimiento_inventario>();
            this.cat_tipos_movimiento_inventario11 = new HashSet<cat_tipos_movimiento_inventario>();
            this.doc_inv_movimiento = new HashSet<doc_inv_movimiento>();
        }
    
        public int TipoMovimientoInventarioId { get; set; }
        public string Descripcion { get; set; }
        public bool Activo { get; set; }
        public Nullable<bool> EsEntrada { get; set; }
        public Nullable<int> TipoMovimientoCancelacionId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cat_tipos_movimiento_inventario> cat_tipos_movimiento_inventario1 { get; set; }
        public virtual cat_tipos_movimiento_inventario cat_tipos_movimiento_inventario2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cat_tipos_movimiento_inventario> cat_tipos_movimiento_inventario11 { get; set; }
        public virtual cat_tipos_movimiento_inventario cat_tipos_movimiento_inventario3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<doc_inv_movimiento> doc_inv_movimiento { get; set; }
    }
}
