//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConexionBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class cat_centro_costos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cat_centro_costos()
        {
            this.cat_gastos = new HashSet<cat_gastos>();
            this.cat_gastos1 = new HashSet<cat_gastos>();
            this.doc_gastos = new HashSet<doc_gastos>();
        }
    
        public int Clave { get; set; }
        public string Descripcion { get; set; }
        public Nullable<bool> Estatus { get; set; }
        public Nullable<int> Empresa { get; set; }
        public Nullable<int> Sucursal { get; set; }
    
        public virtual cat_empresas cat_empresas { get; set; }
        public virtual cat_empresas cat_empresas1 { get; set; }
        public virtual cat_empresas cat_empresas2 { get; set; }
        public virtual cat_empresas cat_empresas3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cat_gastos> cat_gastos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cat_gastos> cat_gastos1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<doc_gastos> doc_gastos { get; set; }
    }
}
