//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConexionBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class cat_productos_precios
    {
        public int IdProductoPrecio { get; set; }
        public int IdProducto { get; set; }
        public byte IdPrecio { get; set; }
        public decimal PorcDescuento { get; set; }
        public decimal MontoDescuento { get; set; }
        public decimal Precio { get; set; }
    
        public virtual cat_precios cat_precios { get; set; }
        public virtual cat_productos cat_productos { get; set; }
    }
}
