//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConexionBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class cat_tipos_documento
    {
        public byte TipoDocumentoId { get; set; }
        public string Descripcion { get; set; }
        public string Abreviatura { get; set; }
        public int FolioInicial { get; set; }
        public bool RequiereClaveSuper { get; set; }
        public bool IntegrarCorteCaja { get; set; }
    }
}
