//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConexionBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class cat_rest_platillo_adicionales_sfam
    {
        public int PlatilloAdicionalId { get; set; }
        public int SubfamiliaId { get; set; }
        public System.DateTime CreadoEl { get; set; }
    
        public virtual cat_rest_platillo_adicionales cat_rest_platillo_adicionales { get; set; }
        public virtual cat_subfamilias cat_subfamilias { get; set; }
    }
}
