//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConexionBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class cat_clientes_automovil
    {
        public int ClienteAutoId { get; set; }
        public int ClienteId { get; set; }
        public string Modelo { get; set; }
        public string Color { get; set; }
        public string Placas { get; set; }
        public string Observaciones { get; set; }
        public System.DateTime CreadoEl { get; set; }
    
        public virtual cat_clientes cat_clientes { get; set; }
    }
}
