//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConexionBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class cat_productos_agrupados_detalle
    {
        public int ProductoAgrupadoId { get; set; }
        public int ProductoId { get; set; }
        public System.DateTime CreadoEl { get; set; }
    
        public virtual cat_productos cat_productos { get; set; }
        public virtual cat_productos_agrupados cat_productos_agrupados { get; set; }
    }
}
