//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConexionBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class cat_cajas_impresora
    {
        public int CajaImpresoraId { get; set; }
        public int CajaId { get; set; }
        public short ImpresoraId { get; set; }
        public System.DateTime CreadoEl { get; set; }
    
        public virtual cat_cajas cat_cajas { get; set; }
        public virtual cat_impresoras cat_impresoras { get; set; }
    }
}
