//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConexionBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class cat_productos_impuestos
    {
        public int ProductoImpuestoId { get; set; }
        public int ProductoId { get; set; }
        public int ImpuestoId { get; set; }
    
        public virtual cat_impuestos cat_impuestos { get; set; }
        public virtual cat_productos cat_productos { get; set; }
    }
}
