//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConexionBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class cat_unidades_medida_SAT
    {
        public int IdUnidadMedidaSAT { get; set; }
        public string ClaveSAT { get; set; }
        public string NombreSAT { get; set; }
        public string DescripcionSAT { get; set; }
        public bool Activo { get; set; }
    }
}
