//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConexionBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class cat_web_configuracion
    {
        public int SucursalId { get; set; }
        public string Dominio { get; set; }
        public string ServidorFTP { get; set; }
        public string UsuarioFTP { get; set; }
        public string PasswordFTP { get; set; }
        public string FolderProductos { get; set; }
        public Nullable<byte> DiasEntregaPedido { get; set; }
        public Nullable<byte> DiasEntregaAdicSPedido { get; set; }
    
        public virtual cat_sucursales cat_sucursales { get; set; }
    }
}
