//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConexionBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class cat_tipos_documento
    {
        public byte TipoDocumentoId { get; set; }
        public string Descripcion { get; set; }
        public string Abreviatura { get; set; }
        public int FolioInicial { get; set; }
        public bool RequiereClaveSuper { get; set; }
        public bool IntegrarCorteCaja { get; set; }
    }
}
