//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConexionBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class cat_formas_pago
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cat_formas_pago()
        {
            this.doc_apartados_formas_pago = new HashSet<doc_apartados_formas_pago>();
            this.doc_ventas_formas_pago = new HashSet<doc_ventas_formas_pago>();
            this.doc_pagos = new HashSet<doc_pagos>();
        }
    
        public int FormaPagoId { get; set; }
        public string Descripcion { get; set; }
        public string Abreviatura { get; set; }
        public short Orden { get; set; }
        public bool RequiereDigVerificador { get; set; }
        public bool Activo { get; set; }
        public string Signo { get; set; }
        public short NumeroHacienda { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<doc_apartados_formas_pago> doc_apartados_formas_pago { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<doc_ventas_formas_pago> doc_ventas_formas_pago { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<doc_pagos> doc_pagos { get; set; }
    }
}
