//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConexionBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class cat_empresas_config_inventario
    {
        public int EmpresaId { get; set; }
        public bool EnableTraspasoAutomatico { get; set; }
        public Nullable<bool> ValidarExistenciaTraspaso { get; set; }
    
        public virtual cat_empresas cat_empresas { get; set; }
        public virtual cat_empresas_config_inventario cat_empresas_config_inventario1 { get; set; }
        public virtual cat_empresas_config_inventario cat_empresas_config_inventario2 { get; set; }
    }
}
