//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConexionBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class cat_tipos_bascula_bitacora
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cat_tipos_bascula_bitacora()
        {
            this.doc_basculas_bitacora = new HashSet<doc_basculas_bitacora>();
        }
    
        public int TipoBasculaBitacoraId { get; set; }
        public string Nombre { get; set; }
        public System.DateTime CreadoEl { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<doc_basculas_bitacora> doc_basculas_bitacora { get; set; }
    }
}
