//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConexionBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class cat_clientes_direcciones
    {
        public int ClienteDireccionId { get; set; }
        public int ClienteId { get; set; }
        public byte TipoDireccionId { get; set; }
        public string Calle { get; set; }
        public string NumeroInterior { get; set; }
        public string NumeroExterior { get; set; }
        public string Colonia { get; set; }
        public string Ciudad { get; set; }
        public Nullable<int> EstadoId { get; set; }
        public Nullable<int> PaisId { get; set; }
        public string CodigoPostal { get; set; }
        public Nullable<System.DateTime> CreadoEl { get; set; }
    
        public virtual cat_clientes cat_clientes { get; set; }
        public virtual cat_estados cat_estados { get; set; }
    }
}
