//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConexionBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class cat_productos_config_sucursal
    {
        public int ProductoId { get; set; }
        public int SucursalId { get; set; }
        public bool CalculaPrecioPorcUtilidad { get; set; }
        public bool CalculaPrecioIncUtilidad { get; set; }
        public bool CalculaPrecioManual { get; set; }
        public decimal PorcUtilidadValor { get; set; }
        public decimal IncUtilidadValor { get; set; }
        public int CreadoPor { get; set; }
        public System.DateTime CreadoEl { get; set; }
        public Nullable<int> ModificadoPor { get; set; }
        public Nullable<System.DateTime> ModificadoEl { get; set; }
    
        public virtual cat_productos cat_productos { get; set; }
        public virtual cat_sucursales cat_sucursales { get; set; }
        public virtual cat_usuarios cat_usuarios { get; set; }
        public virtual cat_usuarios cat_usuarios1 { get; set; }
    }
}
