//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConexionBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class cat_productos_precios
    {
        public int IdProductoPrecio { get; set; }
        public int IdProducto { get; set; }
        public byte IdPrecio { get; set; }
        public decimal PorcDescuento { get; set; }
        public decimal MontoDescuento { get; set; }
        public decimal Precio { get; set; }
    
        public virtual cat_precios cat_precios { get; set; }
        public virtual cat_productos cat_productos { get; set; }
    }
}
