//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConexionBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class cat_sucursales_departamentos
    {
        public int SucursalId { get; set; }
        public int DepartamentoId { get; set; }
        public System.DateTime CreadoEl { get; set; }
        public int CreadoPor { get; set; }
    
        public virtual cat_departamentos cat_departamentos { get; set; }
        public virtual cat_sucursales cat_sucursales { get; set; }
    }
}
