//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConexionBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class cat_productos_impuestos
    {
        public int ProductoImpuestoId { get; set; }
        public int ProductoId { get; set; }
        public int ImpuestoId { get; set; }
    
        public virtual cat_impuestos cat_impuestos { get; set; }
        public virtual cat_productos cat_productos { get; set; }
    }
}
