//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConexionBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class cat_productos_base_conceptos
    {
        public int Id { get; set; }
        public int ProductoId { get; set; }
        public int ConceptoId { get; set; }
        public Nullable<bool> RegistrarTiempo { get; set; }
        public Nullable<bool> RegistrarVolumen { get; set; }
        public string CreadoEl { get; set; }
    
        public virtual cat_conceptos cat_conceptos { get; set; }
        public virtual cat_productos cat_productos { get; set; }
    }
}
