//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConexionBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class cat_equipos_computo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cat_equipos_computo()
        {
            this.doc_equipo_computo_bascula_registro = new HashSet<doc_equipo_computo_bascula_registro>();
        }
    
        public int EquipoComputoId { get; set; }
        public string HardwareID { get; set; }
        public string IPPublica { get; set; }
        public string PCName { get; set; }
        public System.DateTime CreadoEl { get; set; }
        public Nullable<System.DateTime> ModificadoEl { get; set; }
    
        public virtual cat_basculas_configuracion cat_basculas_configuracion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<doc_equipo_computo_bascula_registro> doc_equipo_computo_bascula_registro { get; set; }
    }
}
