//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConexionBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class doc_cargos_detalle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public doc_cargos_detalle()
        {
            this.doc_ventas_detalle = new HashSet<doc_ventas_detalle>();
            this.doc_web_carrito_detalle = new HashSet<doc_web_carrito_detalle>();
        }
    
        public int CargoDetalleId { get; set; }
        public int CargoId { get; set; }
        public System.DateTime FechaCargo { get; set; }
        public Nullable<System.DateTime> FechaPago { get; set; }
        public decimal Subtotal { get; set; }
        public decimal Impuestos { get; set; }
        public decimal Total { get; set; }
        public System.DateTime CreadoEl { get; set; }
        public Nullable<decimal> Saldo { get; set; }
        public Nullable<decimal> Descuento { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<doc_ventas_detalle> doc_ventas_detalle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<doc_web_carrito_detalle> doc_web_carrito_detalle { get; set; }
        public virtual doc_cargos doc_cargos { get; set; }
    }
}
