//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConexionBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class doc_promociones_excepcion
    {
        public int PromocionExcepcionId { get; set; }
        public int PromocionId { get; set; }
        public Nullable<int> LineaId { get; set; }
        public Nullable<int> FamiliaId { get; set; }
        public Nullable<int> Subfamilia { get; set; }
        public Nullable<int> ProductoId { get; set; }
        public System.DateTime CreadoEl { get; set; }
    
        public virtual cat_familias cat_familias { get; set; }
        public virtual cat_lineas cat_lineas { get; set; }
        public virtual cat_productos cat_productos { get; set; }
        public virtual cat_subfamilias cat_subfamilias { get; set; }
        public virtual doc_promociones doc_promociones { get; set; }
    }
}
