//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConexionBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class doc_web_carrito
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public doc_web_carrito()
        {
            this.doc_web_carrito_detalle = new HashSet<doc_web_carrito_detalle>();
        }
    
        public string uUID { get; set; }
        public int id { get; set; }
        public string Email { get; set; }
        public decimal Total { get; set; }
        public System.DateTime CreadoEl { get; set; }
        public string EnvioCalle { get; set; }
        public string EnvioColonia { get; set; }
        public string EnvioCiudad { get; set; }
        public int EnvioEstadoId { get; set; }
        public string EnvioCP { get; set; }
        public string EnvioPersonaRecibe { get; set; }
        public string EnvioTelefonoContacto { get; set; }
        public Nullable<int> ClienteId { get; set; }
        public Nullable<decimal> Impuestos { get; set; }
        public Nullable<decimal> Subtotal { get; set; }
        public Nullable<bool> Pagado { get; set; }
        public Nullable<System.DateTime> FechaPago { get; set; }
        public Nullable<long> VentaId { get; set; }
        public string MontoPaypal { get; set; }
        public string TransactionRef { get; set; }
        public Nullable<System.DateTime> FechaEstimadaEntrega { get; set; }
        public Nullable<System.DateTime> EntregadoEl { get; set; }
        public Nullable<byte> FormaPagoId { get; set; }
    
        public virtual cat_clientes cat_clientes { get; set; }
        public virtual cat_estados cat_estados { get; set; }
        public virtual doc_ventas doc_ventas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<doc_web_carrito_detalle> doc_web_carrito_detalle { get; set; }
    }
}
