//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConexionBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class doc_cocimientos_grupos_movs_inventario
    {
        public int CocimientoGrupoId { get; set; }
        public int MovimientoInventarioId { get; set; }
        public System.DateTime CreadoEl { get; set; }
    
        public virtual doc_cocimientos_grupos doc_cocimientos_grupos { get; set; }
        public virtual doc_inv_movimiento doc_inv_movimiento { get; set; }
    }
}
