//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConexionBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class doc_produccion_conceptos
    {
        public int ProduccionConceptoId { get; set; }
        public int ProduccionId { get; set; }
        public int ConceptoId { get; set; }
        public Nullable<System.DateTime> Inicio { get; set; }
        public Nullable<System.DateTime> Fin { get; set; }
        public Nullable<decimal> Cantidad { get; set; }
        public System.DateTime CreadoEl { get; set; }
        public int CreadoPor { get; set; }
        public Nullable<System.DateTime> ModificadoEl { get; set; }
        public Nullable<int> ModificadoPor { get; set; }
        public Nullable<double> ValorRango1_1 { get; set; }
        public Nullable<double> ValorRango1_2 { get; set; }
    
        public virtual cat_conceptos cat_conceptos { get; set; }
        public virtual cat_usuarios cat_usuarios { get; set; }
        public virtual cat_usuarios cat_usuarios1 { get; set; }
        public virtual doc_produccion doc_produccion { get; set; }
    }
}
