//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConexionBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class doc_productos_sobrantes_regitro_inventario
    {
        public int Id { get; set; }
        public Nullable<int> SobranteRegsitroId { get; set; }
        public Nullable<int> MovimientoDetalleId { get; set; }
        public Nullable<System.DateTime> CreadoEl { get; set; }
    
        public virtual doc_inv_movimiento_detalle doc_inv_movimiento_detalle { get; set; }
        public virtual doc_productos_sobrantes_registro doc_productos_sobrantes_registro { get; set; }
    }
}
