//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConexionBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class doc_devoluciones
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public doc_devoluciones()
        {
            this.doc_devoluciones_detalle = new HashSet<doc_devoluciones_detalle>();
            this.doc_devoluciones_detalle1 = new HashSet<doc_devoluciones_detalle>();
            this.doc_ventas_formas_pago_vale = new HashSet<doc_ventas_formas_pago_vale>();
        }
    
        public int DevolucionId { get; set; }
        public long VentaId { get; set; }
        public decimal Total { get; set; }
        public System.DateTime CreadoEl { get; set; }
        public int CreadoPor { get; set; }
        public Nullable<int> TipoDevolucionId { get; set; }
        public Nullable<System.DateTime> FechaVencimiento { get; set; }
    
        public virtual cat_tipos_devolucion cat_tipos_devolucion { get; set; }
        public virtual cat_tipos_devolucion cat_tipos_devolucion1 { get; set; }
        public virtual cat_usuarios cat_usuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<doc_devoluciones_detalle> doc_devoluciones_detalle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<doc_devoluciones_detalle> doc_devoluciones_detalle1 { get; set; }
        public virtual doc_ventas doc_ventas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<doc_ventas_formas_pago_vale> doc_ventas_formas_pago_vale { get; set; }
    }
}
