//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConexionBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class doc_corte_caja_pedidos_sin_cerrar
    {
        public int CorteCajaId { get; set; }
        public int PedidoId { get; set; }
        public System.DateTime CreadoEl { get; set; }
    
        public virtual doc_corte_caja doc_corte_caja { get; set; }
        public virtual doc_pedidos_orden doc_pedidos_orden { get; set; }
    }
}
