//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConexionBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class doc_corte_caja_egresos
    {
        public int CorteCajaId { get; set; }
        public decimal Gastos { get; set; }
    
        public virtual doc_corte_caja doc_corte_caja { get; set; }
    }
}
