//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConexionBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class doc_pedidos_orden_detalle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public doc_pedidos_orden_detalle()
        {
            this.doc_pedidos_orden_adicional = new HashSet<doc_pedidos_orden_adicional>();
            this.doc_pedidos_orden_ingre = new HashSet<doc_pedidos_orden_ingre>();
            this.doc_basculas_bitacora = new HashSet<doc_basculas_bitacora>();
            this.doc_pedidos_orden_detalle_impresion = new HashSet<doc_pedidos_orden_detalle_impresion>();
        }
    
        public int PedidoDetalleId { get; set; }
        public int PedidoId { get; set; }
        public int ProductoId { get; set; }
        public decimal Cantidad { get; set; }
        public decimal PrecioUnitario { get; set; }
        public decimal PorcDescuento { get; set; }
        public decimal Descuento { get; set; }
        public decimal Impuestos { get; set; }
        public string Notas { get; set; }
        public decimal Total { get; set; }
        public int CreadoPor { get; set; }
        public System.DateTime CreadoEl { get; set; }
        public decimal TasaIVA { get; set; }
        public Nullable<bool> Impreso { get; set; }
        public Nullable<int> ComandaId { get; set; }
        public Nullable<bool> Parallevar { get; set; }
        public Nullable<bool> Cancelado { get; set; }
        public Nullable<byte> TipoDescuentoId { get; set; }
        public Nullable<int> PromocionCMId { get; set; }
        public Nullable<short> CargoAdicionalId { get; set; }
        public string Descripcion { get; set; }
        public Nullable<decimal> CargoAdicionalMonto { get; set; }
        public Nullable<decimal> CantidadOriginal { get; set; }
        public Nullable<decimal> CantidadDevolucion { get; set; }
    
        public virtual cat_productos cat_productos { get; set; }
        public virtual doc_pedidos_orden doc_pedidos_orden { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<doc_pedidos_orden_adicional> doc_pedidos_orden_adicional { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<doc_pedidos_orden_ingre> doc_pedidos_orden_ingre { get; set; }
        public virtual cat_rest_comandas cat_rest_comandas { get; set; }
        public virtual cat_tipos_descuento cat_tipos_descuento { get; set; }
        public virtual doc_promociones_cm doc_promociones_cm { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<doc_basculas_bitacora> doc_basculas_bitacora { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<doc_pedidos_orden_detalle_impresion> doc_pedidos_orden_detalle_impresion { get; set; }
    }
}
