//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConexionBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class doc_productos_compra_cargos
    {
        public int Id { get; set; }
        public int ProductoCompraId { get; set; }
        public int ProductoId { get; set; }
        public string Remision { get; set; }
        public System.DateTime Fecha { get; set; }
        public int ProveedorId { get; set; }
        public decimal Total { get; set; }
        public int CreadoPor { get; set; }
    
        public virtual cat_productos cat_productos { get; set; }
        public virtual cat_proveedores cat_proveedores { get; set; }
        public virtual doc_productos_compra doc_productos_compra { get; set; }
    }
}
