//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConexionBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class doc_productos_sobrantes_config
    {
        public int Id { get; set; }
        public int EmpresaId { get; set; }
        public int ProductoSobranteId { get; set; }
        public int ProductoConvertirId { get; set; }
        public Nullable<bool> Convertir { get; set; }
        public Nullable<System.DateTime> CreadoEl { get; set; }
        public Nullable<int> CreadoPor { get; set; }
        public Nullable<bool> DejarEnCero { get; set; }
    
        public virtual cat_productos cat_productos { get; set; }
        public virtual cat_productos cat_productos1 { get; set; }
        public virtual cat_usuarios cat_usuarios { get; set; }
    }
}
