//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConexionBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class doc_produccion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public doc_produccion()
        {
            this.doc_produccion_entrada = new HashSet<doc_produccion_entrada>();
            this.doc_produccion_salida = new HashSet<doc_produccion_salida>();
            this.doc_produccion_conceptos = new HashSet<doc_produccion_conceptos>();
            this.doc_produccion_solicitud = new HashSet<doc_produccion_solicitud>();
            this.doc_cocimientos = new HashSet<doc_cocimientos>();
            this.doc_produccion_movs_inventario = new HashSet<doc_produccion_movs_inventario>();
        }
    
        public int ProduccionId { get; set; }
        public int SucursalId { get; set; }
        public System.DateTime FechaHoraInicio { get; set; }
        public Nullable<System.DateTime> FechaHoraFin { get; set; }
        public int CreadoPor { get; set; }
        public System.DateTime CreadoEl { get; set; }
        public bool Completado { get; set; }
        public bool Activo { get; set; }
        public int EstatusProduccionId { get; set; }
        public Nullable<int> ProductoId { get; set; }
        public Nullable<int> ProduccionSolicitudId { get; set; }
    
        public virtual cat_sucursales cat_sucursales { get; set; }
        public virtual cat_usuarios cat_usuarios { get; set; }
        public virtual cat_estatus_produccion cat_estatus_produccion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<doc_produccion_entrada> doc_produccion_entrada { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<doc_produccion_salida> doc_produccion_salida { get; set; }
        public virtual cat_productos cat_productos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<doc_produccion_conceptos> doc_produccion_conceptos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<doc_produccion_solicitud> doc_produccion_solicitud { get; set; }
        public virtual doc_produccion_solicitud doc_produccion_solicitud1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<doc_cocimientos> doc_cocimientos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<doc_produccion_movs_inventario> doc_produccion_movs_inventario { get; set; }
    }
}
