//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConexionBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class doc_apartados_pagos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public doc_apartados_pagos()
        {
            this.doc_apartados_formas_pago = new HashSet<doc_apartados_formas_pago>();
            this.doc_corte_caja_apartados_pagos = new HashSet<doc_corte_caja_apartados_pagos>();
        }
    
        public int ApartadoPagoId { get; set; }
        public int ApartadoId { get; set; }
        public decimal Importe { get; set; }
        public System.DateTime FechaPago { get; set; }
        public int CreadoPor { get; set; }
        public bool Anticipo { get; set; }
        public Nullable<int> CajaId { get; set; }
    
        public virtual cat_cajas cat_cajas { get; set; }
        public virtual cat_usuarios cat_usuarios { get; set; }
        public virtual doc_apartados doc_apartados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<doc_apartados_formas_pago> doc_apartados_formas_pago { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<doc_corte_caja_apartados_pagos> doc_corte_caja_apartados_pagos { get; set; }
    }
}
