//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConexionBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class doc_pedidos_orden_programacion
    {
        public int PedidoProgramacionId { get; set; }
        public int PedidoId { get; set; }
        public int ClienteId { get; set; }
        public System.DateTime FechaProgramada { get; set; }
        public System.TimeSpan HoraProgramada { get; set; }
        public int CreadoEl { get; set; }
        public int CreadoPor { get; set; }
    
        public virtual cat_clientes cat_clientes { get; set; }
        public virtual cat_usuarios cat_usuarios { get; set; }
        public virtual doc_pedidos_orden doc_pedidos_orden { get; set; }
    }
}
