//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConexionBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class doc_apartados
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public doc_apartados()
        {
            this.doc_apartados_pagos = new HashSet<doc_apartados_pagos>();
            this.doc_apartados_productos = new HashSet<doc_apartados_productos>();
        }
    
        public int ApartadoId { get; set; }
        public int SucursalId { get; set; }
        public int ClienteId { get; set; }
        public decimal TotalApartado { get; set; }
        public decimal Saldo { get; set; }
        public bool Activo { get; set; }
        public System.DateTime CreadoEl { get; set; }
        public int CreadoPor { get; set; }
        public Nullable<System.DateTime> FechaLimite { get; set; }
        public Nullable<System.DateTime> FechaProrroga { get; set; }
        public Nullable<long> VentaId { get; set; }
        public Nullable<int> CajaId { get; set; }
    
        public virtual cat_clientes cat_clientes { get; set; }
        public virtual cat_sucursales cat_sucursales { get; set; }
        public virtual cat_usuarios cat_usuarios { get; set; }
        public virtual doc_ventas doc_ventas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<doc_apartados_pagos> doc_apartados_pagos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<doc_apartados_productos> doc_apartados_productos { get; set; }
    }
}
