//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConexionBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class doc_pagos
    {
        public int PagoId { get; set; }
        public Nullable<int> ClienteId { get; set; }
        public Nullable<int> CargoId { get; set; }
        public System.DateTime FechaPago { get; set; }
        public int FormaPagoId { get; set; }
        public decimal Monto { get; set; }
        public System.DateTime CreadoEl { get; set; }
        public int CreadoPor { get; set; }
        public Nullable<bool> Activo { get; set; }
    
        public virtual cat_clientes cat_clientes { get; set; }
        public virtual cat_formas_pago cat_formas_pago { get; set; }
        public virtual cat_usuarios cat_usuarios { get; set; }
        public virtual doc_cargos doc_cargos { get; set; }
    }
}
