//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConexionBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class doc_retiros
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public doc_retiros()
        {
            this.doc_retiros_denominaciones = new HashSet<doc_retiros_denominaciones>();
        }
    
        public int RetiroId { get; set; }
        public System.DateTime FechaRetiro { get; set; }
        public decimal MontoRetiro { get; set; }
        public int CreadoPor { get; set; }
        public int CajaId { get; set; }
        public int SucursalId { get; set; }
        public string Observaciones { get; set; }
    
        public virtual cat_cajas cat_cajas { get; set; }
        public virtual cat_sucursales cat_sucursales { get; set; }
        public virtual cat_usuarios cat_usuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<doc_retiros_denominaciones> doc_retiros_denominaciones { get; set; }
    }
}
