//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConexionBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class doc_promociones_cm_detalle
    {
        public int PromocionCMDetId { get; set; }
        public int PromocionCMId { get; set; }
        public int ProductoId { get; set; }
        public decimal CantidadCompraMinima { get; set; }
        public decimal CantidadCobro { get; set; }
        public System.DateTime CreadoEL { get; set; }
    
        public virtual cat_productos cat_productos { get; set; }
        public virtual doc_promociones_cm doc_promociones_cm { get; set; }
    }
}
