//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConexionBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class doc_precios_especiales
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public doc_precios_especiales()
        {
            this.doc_precios_especiales_detalle = new HashSet<doc_precios_especiales_detalle>();
        }
    
        public int Id { get; set; }
        public string Descripcion { get; set; }
        public System.DateTime FechaVigencia { get; set; }
        public System.DateTime HoraVigencia { get; set; }
        public System.DateTime CreadoEl { get; set; }
        public int CreadoPor { get; set; }
        public Nullable<int> SucursalId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<doc_precios_especiales_detalle> doc_precios_especiales_detalle { get; set; }
        public virtual cat_sucursales cat_sucursales { get; set; }
    }
}
