//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConexionBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class doc_aceptaciones_sucursal_detalle
    {
        public int Id { get; set; }
        public int AceptacionSucursalId { get; set; }
        public Nullable<int> MovimientoDetalleId { get; set; }
        public Nullable<decimal> CantidadReal { get; set; }
        public int MovimientoDetalleAjusteId { get; set; }
        public System.DateTime CreadoEl { get; set; }
        public int CreadoPor { get; set; }
    
        public virtual cat_usuarios cat_usuarios { get; set; }
        public virtual doc_aceptaciones_sucursal doc_aceptaciones_sucursal { get; set; }
        public virtual doc_inv_movimiento_detalle doc_inv_movimiento_detalle { get; set; }
        public virtual doc_inv_movimiento_detalle doc_inv_movimiento_detalle1 { get; set; }
    }
}
