//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConexionBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class doc_clientes_productos_precios
    {
        public int ClienteProductoPrecioId { get; set; }
        public Nullable<int> ClienteId { get; set; }
        public Nullable<int> ProductoId { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public Nullable<System.DateTime> CreadoEl { get; set; }
    
        public virtual cat_clientes cat_clientes { get; set; }
        public virtual cat_productos cat_productos { get; set; }
    }
}
