//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConexionBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class doc_cargo_adicional_config
    {
        public short CargoAdicionalId { get; set; }
        public int SucursalId { get; set; }
        public Nullable<decimal> PorcentajeVenta { get; set; }
        public Nullable<decimal> MontoFijo { get; set; }
        public bool Activo { get; set; }
        public string CreadoEl { get; set; }
    
        public virtual cat_cargos_adicionales cat_cargos_adicionales { get; set; }
        public virtual cat_sucursales cat_sucursales { get; set; }
    }
}
