//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConexionBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class doc_produccion_entrada
    {
        public int ProduccionId { get; set; }
        public int ProductoId { get; set; }
        public decimal Cantidad { get; set; }
        public int UnidadId { get; set; }
        public System.DateTime CreadoEl { get; set; }
        public int Id { get; set; }
    
        public virtual cat_productos cat_productos { get; set; }
        public virtual cat_unidadesmed cat_unidadesmed { get; set; }
        public virtual doc_produccion doc_produccion { get; set; }
    }
}
