//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConexionBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class doc_maiz_maseca_rendimiento
    {
        public int Id { get; set; }
        public int SucursalId { get; set; }
        public System.DateTime Fecha { get; set; }
        public double MaizSacos { get; set; }
        public double MasecaSacos { get; set; }
        public double TortillaMaizRendimiento { get; set; }
        public double TortillaMasecaRendimiento { get; set; }
        public double TortillaTotalRendimiento { get; set; }
        public System.DateTime CreadoEl { get; set; }
        public int CreadoPor { get; set; }
        public Nullable<System.DateTime> ModificadoEl { get; set; }
        public Nullable<int> ModificadoPor { get; set; }
    
        public virtual cat_sucursales cat_sucursales { get; set; }
        public virtual cat_usuarios cat_usuarios { get; set; }
        public virtual cat_usuarios cat_usuarios1 { get; set; }
    }
}
