//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConexionBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class doc_corte_caja_ventas
    {
        public int CorteId { get; set; }
        public int VentaId { get; set; }
        public System.DateTime CreadoEl { get; set; }
    }
}
