//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConexionBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class doc_reimpresion_ticket
    {
        public int ReimpresionTicketId { get; set; }
        public System.DateTime FechaReimpresion { get; set; }
        public long VentaId { get; set; }
        public System.DateTime CreadoEl { get; set; }
        public int CreadoPor { get; set; }
        public int CajaId { get; set; }
    
        public virtual cat_cajas cat_cajas { get; set; }
        public virtual doc_ventas doc_ventas { get; set; }
    }
}
