//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConexionBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class doc_promociones_cm_detalle
    {
        public int PromocionCMDetId { get; set; }
        public int PromocionCMId { get; set; }
        public int ProductoId { get; set; }
        public decimal CantidadCompraMinima { get; set; }
        public decimal CantidadCobro { get; set; }
        public System.DateTime CreadoEL { get; set; }
    
        public virtual cat_productos cat_productos { get; set; }
        public virtual doc_promociones_cm doc_promociones_cm { get; set; }
    }
}
