//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConexionBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class doc_productos_compra_detalle
    {
        public int ProductoCompraDetId { get; set; }
        public int ProductoCompraId { get; set; }
        public int ProductoId { get; set; }
        public decimal Cantidad { get; set; }
        public decimal PrecioUnitario { get; set; }
        public decimal PorcImpuestos { get; set; }
        public decimal Impuestos { get; set; }
        public decimal PorcDescuentos { get; set; }
        public decimal Descuentos { get; set; }
        public decimal Subtotal { get; set; }
        public decimal Total { get; set; }
        public System.DateTime CreadoEl { get; set; }
        public int CreadoPor { get; set; }
        public Nullable<decimal> PrecioNeto { get; set; }
        public Nullable<decimal> PrecioCompra { get; set; }
        public Nullable<double> Flete { get; set; }
        public Nullable<double> Comisiones { get; set; }
    
        public virtual cat_productos cat_productos { get; set; }
        public virtual cat_usuarios cat_usuarios { get; set; }
        public virtual doc_productos_compra doc_productos_compra { get; set; }
    }
}
