//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConexionBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class doc_produccion_solicitud_requerido
    {
        public int Id { get; set; }
        public int ProduccionSolicitudDetalleId { get; set; }
        public int ProductoRequeridoId { get; set; }
        public int UnidadRequeridaId { get; set; }
        public double Cantidad { get; set; }
        public System.DateTime CreadoEl { get; set; }
        public int CreadoPor { get; set; }
    
        public virtual cat_productos cat_productos { get; set; }
        public virtual cat_unidadesmed cat_unidadesmed { get; set; }
        public virtual cat_usuarios cat_usuarios { get; set; }
        public virtual doc_produccion_solicitud_detalle doc_produccion_solicitud_detalle { get; set; }
    }
}
