//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConexionBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class doc_equipo_computo_bascula_registro
    {
        public long Id { get; set; }
        public int EquipoConputoId { get; set; }
        public double Peso { get; set; }
        public System.DateTime CreadoEl { get; set; }
        public Nullable<bool> OcupadaPorApp { get; set; }
        public Nullable<int> SucursalId { get; set; }
    
        public virtual cat_equipos_computo cat_equipos_computo { get; set; }
        public virtual cat_sucursales cat_sucursales { get; set; }
    }
}
