//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConexionBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class doc_promociones_cm
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public doc_promociones_cm()
        {
            this.doc_promociones_cm_detalle = new HashSet<doc_promociones_cm_detalle>();
            this.doc_pedidos_orden_detalle = new HashSet<doc_pedidos_orden_detalle>();
            this.doc_ventas_detalle = new HashSet<doc_ventas_detalle>();
        }
    
        public int PromocionCMId { get; set; }
        public string NombrePromocion { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public System.DateTime FechaVigencia { get; set; }
        public System.TimeSpan HoraVigencia { get; set; }
        public Nullable<bool> Lunes { get; set; }
        public Nullable<bool> Martes { get; set; }
        public Nullable<bool> Miercoles { get; set; }
        public Nullable<bool> Jueves { get; set; }
        public Nullable<bool> Viernes { get; set; }
        public Nullable<bool> Sabado { get; set; }
        public Nullable<bool> Domingo { get; set; }
        public int CreadoPor { get; set; }
        public bool Activo { get; set; }
        public int SucursalId { get; set; }
    
        public virtual cat_usuarios cat_usuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<doc_promociones_cm_detalle> doc_promociones_cm_detalle { get; set; }
        public virtual cat_sucursales cat_sucursales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<doc_pedidos_orden_detalle> doc_pedidos_orden_detalle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<doc_ventas_detalle> doc_ventas_detalle { get; set; }
    }
}
