//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConexionBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class doc_devoluciones_detalle
    {
        public int DevolucionDetId { get; set; }
        public int DevolucionId { get; set; }
        public long VentaId { get; set; }
        public int ProductoId { get; set; }
        public decimal Cantidad { get; set; }
        public decimal Total { get; set; }
        public System.DateTime CreadoEl { get; set; }
        public int CreadoPor { get; set; }
    
        public virtual cat_usuarios cat_usuarios { get; set; }
        public virtual doc_devoluciones doc_devoluciones { get; set; }
        public virtual doc_devoluciones doc_devoluciones1 { get; set; }
        public virtual doc_ventas doc_ventas { get; set; }
        public virtual doc_ventas doc_ventas1 { get; set; }
    }
}
