//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConexionBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class doc_corte_caja
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public doc_corte_caja()
        {
            this.doc_corte_caja_apartados_pagos = new HashSet<doc_corte_caja_apartados_pagos>();
            this.doc_corte_caja_denominaciones = new HashSet<doc_corte_caja_denominaciones>();
            this.doc_corte_caja_fp_apartado = new HashSet<doc_corte_caja_fp_apartado>();
            this.doc_corte_caja_fp = new HashSet<doc_corte_caja_fp>();
            this.doc_declaracion_fondo_inicial = new HashSet<doc_declaracion_fondo_inicial>();
            this.doc_corte_caja_pedidos_sin_cerrar = new HashSet<doc_corte_caja_pedidos_sin_cerrar>();
            this.doc_sesiones_punto_venta = new HashSet<doc_sesiones_punto_venta>();
        }
    
        public int CorteCajaId { get; set; }
        public int CajaId { get; set; }
        public System.DateTime CreadoEl { get; set; }
        public int CreadoPor { get; set; }
        public Nullable<long> VentaIniId { get; set; }
        public Nullable<long> VentaFinId { get; set; }
        public System.DateTime FechaApertura { get; set; }
        public System.DateTime FechaCorte { get; set; }
        public decimal TotalCorte { get; set; }
        public decimal TotalIngresos { get; set; }
        public decimal TotalEgresos { get; set; }
    
        public virtual cat_cajas cat_cajas { get; set; }
        public virtual cat_usuarios cat_usuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<doc_corte_caja_apartados_pagos> doc_corte_caja_apartados_pagos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<doc_corte_caja_denominaciones> doc_corte_caja_denominaciones { get; set; }
        public virtual doc_ventas doc_ventas { get; set; }
        public virtual doc_ventas doc_ventas1 { get; set; }
        public virtual doc_corte_caja_egresos doc_corte_caja_egresos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<doc_corte_caja_fp_apartado> doc_corte_caja_fp_apartado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<doc_corte_caja_fp> doc_corte_caja_fp { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<doc_declaracion_fondo_inicial> doc_declaracion_fondo_inicial { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<doc_corte_caja_pedidos_sin_cerrar> doc_corte_caja_pedidos_sin_cerrar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<doc_sesiones_punto_venta> doc_sesiones_punto_venta { get; set; }
    }
}
