//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConexionBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class doc_corte_caja_previo
    {
        public int CorteCajaId { get; set; }
        public int CajaId { get; set; }
        public System.DateTime CreadoEl { get; set; }
        public int CreadoPor { get; set; }
        public Nullable<long> VentaIniId { get; set; }
        public Nullable<long> VentaFinId { get; set; }
        public System.DateTime FechaApertura { get; set; }
        public System.DateTime FechaCorte { get; set; }
        public decimal TotalCorte { get; set; }
        public decimal TotalIngresos { get; set; }
        public decimal TotalEgresos { get; set; }
    }
}
