//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConexionBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class doc_pedidos_cargos
    {
        public int PedidoCargoId { get; set; }
        public int PedidoId { get; set; }
        public int CargoId { get; set; }
        public System.DateTime CreadoEl { get; set; }
        public Nullable<int> CreadoPor { get; set; }
    
        public virtual cat_usuarios cat_usuarios { get; set; }
        public virtual doc_cargos doc_cargos { get; set; }
        public virtual doc_pedidos_orden doc_pedidos_orden { get; set; }
    }
}
