//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConexionBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class doc_produccion_salida
    {
        public int ProduccionId { get; set; }
        public int ProductoId { get; set; }
        public Nullable<decimal> Cantidad { get; set; }
        public Nullable<int> UnidadId { get; set; }
        public System.DateTime CreadoEl { get; set; }
        public int Id { get; set; }
    
        public virtual cat_productos cat_productos { get; set; }
        public virtual cat_unidadesmed cat_unidadesmed { get; set; }
        public virtual doc_produccion doc_produccion { get; set; }
    }
}
