//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConexionBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class doc_productos_compra_cargos
    {
        public int Id { get; set; }
        public int ProductoCompraId { get; set; }
        public int ProductoId { get; set; }
        public string Remision { get; set; }
        public System.DateTime Fecha { get; set; }
        public int ProveedorId { get; set; }
        public decimal Total { get; set; }
        public int CreadoPor { get; set; }
    
        public virtual cat_productos cat_productos { get; set; }
        public virtual cat_proveedores cat_proveedores { get; set; }
        public virtual doc_productos_compra doc_productos_compra { get; set; }
    }
}
