//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConexionBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class doc_gastos
    {
        public int GastoId { get; set; }
        public int CentroCostoId { get; set; }
        public int GastoConceptoId { get; set; }
        public string Obervaciones { get; set; }
        public decimal Monto { get; set; }
        public Nullable<int> CajaId { get; set; }
        public System.DateTime CreadoEl { get; set; }
        public int CreadoPor { get; set; }
        public int SucursalId { get; set; }
        public bool Activo { get; set; }
    
        public virtual cat_cajas cat_cajas { get; set; }
        public virtual cat_centro_costos cat_centro_costos { get; set; }
        public virtual cat_gastos cat_gastos { get; set; }
        public virtual cat_sucursales cat_sucursales { get; set; }
        public virtual cat_usuarios cat_usuarios { get; set; }
    }
}
