//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConexionBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class doc_inv_movimiento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public doc_inv_movimiento()
        {
            this.doc_inv_movimiento1 = new HashSet<doc_inv_movimiento>();
            this.doc_inv_movimiento_detalle = new HashSet<doc_inv_movimiento_detalle>();
            this.doc_cocimientos_grupos_movs_inventario = new HashSet<doc_cocimientos_grupos_movs_inventario>();
            this.doc_produccion_movs_inventario = new HashSet<doc_produccion_movs_inventario>();
            this.doc_aceptaciones_sucursal = new HashSet<doc_aceptaciones_sucursal>();
        }
    
        public int MovimientoId { get; set; }
        public int SucursalId { get; set; }
        public string FolioMovimiento { get; set; }
        public int TipoMovimientoId { get; set; }
        public System.DateTime FechaMovimiento { get; set; }
        public System.TimeSpan HoraMovimiento { get; set; }
        public string Comentarios { get; set; }
        public decimal ImporteTotal { get; set; }
        public bool Activo { get; set; }
        public int CreadoPor { get; set; }
        public System.DateTime CreadoEl { get; set; }
        public Nullable<bool> Autorizado { get; set; }
        public Nullable<System.DateTime> FechaAutoriza { get; set; }
        public Nullable<int> SucursalDestinoId { get; set; }
        public Nullable<int> AutorizadoPor { get; set; }
        public Nullable<System.DateTime> FechaCancelacion { get; set; }
        public Nullable<int> ProductoCompraId { get; set; }
        public Nullable<int> Consecutivo { get; set; }
        public Nullable<int> SucursalOrigenId { get; set; }
        public Nullable<long> VentaId { get; set; }
        public Nullable<int> MovimientoRefId { get; set; }
        public Nullable<bool> Cancelado { get; set; }
        public Nullable<short> TipoMermaId { get; set; }
        public Nullable<System.DateTime> FechaCorteExistencia { get; set; }
    
        public virtual cat_sucursales cat_sucursales { get; set; }
        public virtual cat_sucursales cat_sucursales1 { get; set; }
        public virtual cat_sucursales cat_sucursales2 { get; set; }
        public virtual cat_sucursales cat_sucursales3 { get; set; }
        public virtual cat_sucursales cat_sucursales4 { get; set; }
        public virtual cat_sucursales cat_sucursales5 { get; set; }
        public virtual cat_tipos_movimiento_inventario cat_tipos_movimiento_inventario { get; set; }
        public virtual cat_usuarios cat_usuarios { get; set; }
        public virtual cat_usuarios cat_usuarios1 { get; set; }
        public virtual cat_usuarios cat_usuarios2 { get; set; }
        public virtual doc_productos_compra doc_productos_compra { get; set; }
        public virtual doc_productos_compra doc_productos_compra1 { get; set; }
        public virtual doc_ventas doc_ventas { get; set; }
        public virtual doc_ventas doc_ventas1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<doc_inv_movimiento> doc_inv_movimiento1 { get; set; }
        public virtual doc_inv_movimiento doc_inv_movimiento2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<doc_inv_movimiento_detalle> doc_inv_movimiento_detalle { get; set; }
        public virtual cat_tipos_mermas cat_tipos_mermas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<doc_cocimientos_grupos_movs_inventario> doc_cocimientos_grupos_movs_inventario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<doc_produccion_movs_inventario> doc_produccion_movs_inventario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<doc_aceptaciones_sucursal> doc_aceptaciones_sucursal { get; set; }
    }
}
