//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConexionBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class doc_entrada_directa_adicional
    {
        public int MovimientoDetalleId { get; set; }
        public decimal PrecioCompra { get; set; }
    
        public virtual doc_inv_movimiento_detalle doc_inv_movimiento_detalle { get; set; }
    }
}
