//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConexionBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class doc_inv_movimiento_detalle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public doc_inv_movimiento_detalle()
        {
            this.doc_productos_sobrantes_regitro_inventario = new HashSet<doc_productos_sobrantes_regitro_inventario>();
            this.doc_aceptaciones_sucursal_detalle = new HashSet<doc_aceptaciones_sucursal_detalle>();
            this.doc_aceptaciones_sucursal_detalle1 = new HashSet<doc_aceptaciones_sucursal_detalle>();
        }
    
        public int MovimientoDetalleId { get; set; }
        public int MovimientoId { get; set; }
        public int ProductoId { get; set; }
        public int Consecutivo { get; set; }
        public Nullable<decimal> Cantidad { get; set; }
        public decimal PrecioUnitario { get; set; }
        public decimal Importe { get; set; }
        public Nullable<decimal> Disponible { get; set; }
        public int CreadoPor { get; set; }
        public System.DateTime CreadoEl { get; set; }
        public Nullable<decimal> CostoUltimaCompra { get; set; }
        public Nullable<decimal> CostoPromedio { get; set; }
        public Nullable<decimal> ValCostoUltimaCompra { get; set; }
        public Nullable<decimal> ValCostoPromedio { get; set; }
        public Nullable<decimal> ValorMovimiento { get; set; }
        public Nullable<double> Flete { get; set; }
        public Nullable<double> Comisiones { get; set; }
        public Nullable<decimal> SubTotal { get; set; }
        public Nullable<decimal> PrecioNeto { get; set; }
    
        public virtual cat_productos cat_productos { get; set; }
        public virtual cat_usuarios cat_usuarios { get; set; }
        public virtual doc_entrada_directa_adicional doc_entrada_directa_adicional { get; set; }
        public virtual doc_inv_movimiento doc_inv_movimiento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<doc_productos_sobrantes_regitro_inventario> doc_productos_sobrantes_regitro_inventario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<doc_aceptaciones_sucursal_detalle> doc_aceptaciones_sucursal_detalle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<doc_aceptaciones_sucursal_detalle> doc_aceptaciones_sucursal_detalle1 { get; set; }
    }
}
