//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConexionBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class doc_apartados_formas_pago
    {
        public int ApartadoPagoId { get; set; }
        public int FormaPagoId { get; set; }
        public decimal Cantidad { get; set; }
        public string DigitoVerificador { get; set; }
        public System.DateTime CreadoEl { get; set; }
    
        public virtual cat_formas_pago cat_formas_pago { get; set; }
        public virtual doc_apartados_pagos doc_apartados_pagos { get; set; }
    }
}
