//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConexionBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class doc_productos_sobrantes_registro
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public doc_productos_sobrantes_registro()
        {
            this.doc_productos_sobrantes_regitro_inventario = new HashSet<doc_productos_sobrantes_regitro_inventario>();
        }
    
        public int Id { get; set; }
        public Nullable<int> SucursalId { get; set; }
        public Nullable<int> ProductoId { get; set; }
        public Nullable<double> CantidadSobrante { get; set; }
        public Nullable<System.DateTime> CreadoEl { get; set; }
        public Nullable<int> CreadoPor { get; set; }
        public Nullable<bool> Cerrado { get; set; }
        public Nullable<System.DateTime> CerradoEl { get; set; }
        public Nullable<int> CerradoPor { get; set; }
        public Nullable<decimal> CantidadInventario { get; set; }
    
        public virtual cat_productos cat_productos { get; set; }
        public virtual cat_sucursales cat_sucursales { get; set; }
        public virtual cat_usuarios cat_usuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<doc_productos_sobrantes_regitro_inventario> doc_productos_sobrantes_regitro_inventario { get; set; }
        public virtual cat_usuarios cat_usuarios1 { get; set; }
    }
}
