//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConexionBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class doc_cocimientos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public doc_cocimientos()
        {
            this.doc_cocimientos_grupos_detalle = new HashSet<doc_cocimientos_grupos_detalle>();
        }
    
        public int CocimientoId { get; set; }
        public int ProductoId { get; set; }
        public int ProduccionId { get; set; }
        public System.DateTime FechaCocimiento { get; set; }
        public Nullable<System.DateTime> FechaHabilitado { get; set; }
        public System.DateTime CreadoEl { get; set; }
        public int CreadoPor { get; set; }
        public Nullable<System.DateTime> FechaHoraIni { get; set; }
        public Nullable<System.DateTime> FechaHoraFin { get; set; }
    
        public virtual cat_productos cat_productos { get; set; }
        public virtual cat_usuarios cat_usuarios { get; set; }
        public virtual doc_produccion doc_produccion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<doc_cocimientos_grupos_detalle> doc_cocimientos_grupos_detalle { get; set; }
    }
}
