//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConexionBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class doc_corte_caja_datos_entrada
    {
        public int Id { get; set; }
        public int SucursalId { get; set; }
        public decimal TiradaTortilla { get; set; }
        public decimal MasaKg { get; set; }
        public decimal TiradaTortillaKg { get; set; }
        public int CreadoPor { get; set; }
        public System.DateTime CreadoEl { get; set; }
        public Nullable<decimal> MaizKg { get; set; }
        public Nullable<System.DateTime> ModificadoEl { get; set; }
        public Nullable<int> ModificadoPor { get; set; }
    
        public virtual cat_sucursales cat_sucursales { get; set; }
        public virtual cat_usuarios cat_usuarios { get; set; }
    }
}
