//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConexionBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class doc_retiros_denominaciones
    {
        public int RetiroId { get; set; }
        public int DenominacionId { get; set; }
        public int Cantidad { get; set; }
        public decimal ValorDenominacion { get; set; }
        public decimal Total { get; set; }
        public System.DateTime CreadoEl { get; set; }
        public int CreadoPor { get; set; }
    
        public virtual cat_denominaciones cat_denominaciones { get; set; }
        public virtual cat_usuarios cat_usuarios { get; set; }
        public virtual doc_retiros doc_retiros { get; set; }
    }
}
