//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConexionBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class doc_cocimientos_grupos_movs_inventario
    {
        public int CocimientoGrupoId { get; set; }
        public int MovimientoInventarioId { get; set; }
        public System.DateTime CreadoEl { get; set; }
    
        public virtual doc_cocimientos_grupos doc_cocimientos_grupos { get; set; }
        public virtual doc_inv_movimiento doc_inv_movimiento { get; set; }
    }
}
