//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConexionBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class doc_pedidos_orden
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public doc_pedidos_orden()
        {
            this.doc_pedidos_orden_detalle = new HashSet<doc_pedidos_orden_detalle>();
            this.doc_pedidos_orden_mesa = new HashSet<doc_pedidos_orden_mesa>();
            this.doc_pedidos_orden_mesero = new HashSet<doc_pedidos_orden_mesero>();
            this.doc_pedidos_orden_cargos = new HashSet<doc_pedidos_orden_cargos>();
            this.doc_pedidos_orden_programacion = new HashSet<doc_pedidos_orden_programacion>();
            this.doc_corte_caja_pedidos_sin_cerrar = new HashSet<doc_corte_caja_pedidos_sin_cerrar>();
            this.doc_pedidos_cargos = new HashSet<doc_pedidos_cargos>();
        }
    
        public int PedidoId { get; set; }
        public int SucursalId { get; set; }
        public Nullable<int> ComandaId { get; set; }
        public decimal PorcDescuento { get; set; }
        public decimal Subtotal { get; set; }
        public decimal Descuento { get; set; }
        public decimal Impuestos { get; set; }
        public decimal Total { get; set; }
        public Nullable<int> ClienteId { get; set; }
        public string MotivoCancelacion { get; set; }
        public bool Activo { get; set; }
        public System.DateTime CreadoEl { get; set; }
        public int CreadoPor { get; set; }
        public byte Personas { get; set; }
        public System.DateTime FechaApertura { get; set; }
        public System.DateTime FechaCierre { get; set; }
        public Nullable<long> VentaId { get; set; }
        public Nullable<bool> Cancelada { get; set; }
        public Nullable<System.DateTime> FechaCancelacion { get; set; }
        public Nullable<int> CanceladoPor { get; set; }
        public Nullable<bool> UberEats { get; set; }
        public string Para { get; set; }
        public string Notas { get; set; }
        public Nullable<int> CargoId { get; set; }
        public Nullable<int> CajaId { get; set; }
        public Nullable<int> TipoPedidoId { get; set; }
        public string Folio { get; set; }
        public Nullable<bool> Facturar { get; set; }
        public Nullable<int> SucursalCobroId { get; set; }
        public Nullable<bool> Credito { get; set; }
    
        public virtual cat_clientes cat_clientes { get; set; }
        public virtual cat_rest_comandas cat_rest_comandas { get; set; }
        public virtual cat_sucursales cat_sucursales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<doc_pedidos_orden_detalle> doc_pedidos_orden_detalle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<doc_pedidos_orden_mesa> doc_pedidos_orden_mesa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<doc_pedidos_orden_mesero> doc_pedidos_orden_mesero { get; set; }
        public virtual doc_ventas doc_ventas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<doc_pedidos_orden_cargos> doc_pedidos_orden_cargos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<doc_pedidos_orden_programacion> doc_pedidos_orden_programacion { get; set; }
        public virtual doc_cargos doc_cargos { get; set; }
        public virtual cat_usuarios cat_usuarios { get; set; }
        public virtual cat_cajas cat_cajas { get; set; }
        public virtual cat_tipos_pedido cat_tipos_pedido { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<doc_corte_caja_pedidos_sin_cerrar> doc_corte_caja_pedidos_sin_cerrar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<doc_pedidos_cargos> doc_pedidos_cargos { get; set; }
        public virtual cat_sucursales cat_sucursales1 { get; set; }
    }
}
