//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConexionBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class doc_declaracion_fondo_inicial
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public doc_declaracion_fondo_inicial()
        {
            this.doc_declaracion_fondo_inicial_detalle = new HashSet<doc_declaracion_fondo_inicial_detalle>();
        }
    
        public int DeclaracionFondoId { get; set; }
        public int SucursalId { get; set; }
        public Nullable<int> CorteCajaId { get; set; }
        public System.DateTime CreadoEl { get; set; }
        public int CreadoPor { get; set; }
        public Nullable<int> CajaId { get; set; }
        public Nullable<decimal> Total { get; set; }
    
        public virtual cat_sucursales cat_sucursales { get; set; }
        public virtual doc_corte_caja doc_corte_caja { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<doc_declaracion_fondo_inicial_detalle> doc_declaracion_fondo_inicial_detalle { get; set; }
        public virtual cat_cajas cat_cajas { get; set; }
    }
}
