//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConexionBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class doc_produccion_solicitud_aceptacion
    {
        public int ProduccionSolicitudAceptacionId { get; set; }
        public int ProduccionSolicitudDetalleId { get; set; }
        public int UnidadId { get; set; }
        public double Cantidad { get; set; }
        public int AceptadoPor { get; set; }
        public System.DateTime CreadoEl { get; set; }
        public string Comentarios { get; set; }
    
        public virtual cat_unidadesmed cat_unidadesmed { get; set; }
        public virtual cat_usuarios cat_usuarios { get; set; }
        public virtual doc_produccion_solicitud_detalle doc_produccion_solicitud_detalle { get; set; }
    }
}
