//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConexionBD
{
    using System;
    
    public partial class p_rpt_ventas_resumen_Result1
    {
        public Nullable<int> SucursalId { get; set; }
        public string Sucursal { get; set; }
        public string Serie { get; set; }
        public string Folio { get; set; }
        public string Clave { get; set; }
        public System.DateTime FechaHora { get; set; }
        public string Descripcion { get; set; }
        public decimal Cantidad { get; set; }
        public decimal Descuento { get; set; }
        public int Cancelado { get; set; }
        public decimal Total { get; set; }
        public string Cliente { get; set; }
        public string Coche { get; set; }
        public string Observaciones { get; set; }
    }
}
