//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConexionBD
{
    using System;
    
    public partial class p_rpt_corte_caja_descuentos_Result1
    {
        public string Folio { get; set; }
        public Nullable<decimal> Descuento { get; set; }
    }
}
