//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConexionBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class rh_empleados
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public rh_empleados()
        {
            this.cat_usuarios = new HashSet<cat_usuarios>();
            this.rh_empleado_puestos = new HashSet<rh_empleado_puestos>();
            this.doc_pedidos_orden_mesero = new HashSet<doc_pedidos_orden_mesero>();
            this.cat_clientes = new HashSet<cat_clientes>();
            this.doc_empleados_productos_descuentos = new HashSet<doc_empleados_productos_descuentos>();
            this.doc_ventas = new HashSet<doc_ventas>();
        }
    
        public int NumEmpleado { get; set; }
        public string Nombre { get; set; }
        public decimal SueldoNeto { get; set; }
        public Nullable<decimal> SueldoDiario { get; set; }
        public Nullable<decimal> SueldoHra { get; set; }
        public Nullable<int> FormaPago { get; set; }
        public Nullable<int> TipoContrato { get; set; }
        public Nullable<int> Puesto { get; set; }
        public Nullable<int> Departamento { get; set; }
        public Nullable<System.DateTime> FechaIngreso { get; set; }
        public Nullable<System.DateTime> FechaInicioLab { get; set; }
        public Nullable<int> Estatus { get; set; }
        public byte[] Foto { get; set; }
        public Nullable<int> Empresa { get; set; }
        public Nullable<int> Sucursal { get; set; }
    
        public virtual cat_empresas cat_empresas { get; set; }
        public virtual cat_empresas cat_empresas1 { get; set; }
        public virtual cat_empresas cat_empresas2 { get; set; }
        public virtual cat_empresas cat_empresas3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cat_usuarios> cat_usuarios { get; set; }
        public virtual rh_departamentos rh_departamentos { get; set; }
        public virtual rh_departamentos rh_departamentos1 { get; set; }
        public virtual rh_formaspagonom rh_formaspagonom { get; set; }
        public virtual rh_formaspagonom rh_formaspagonom1 { get; set; }
        public virtual rh_puestos rh_puestos { get; set; }
        public virtual rh_puestos rh_puestos1 { get; set; }
        public virtual rh_tipos_contrato rh_tipos_contrato { get; set; }
        public virtual rh_tipos_contrato rh_tipos_contrato1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rh_empleado_puestos> rh_empleado_puestos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<doc_pedidos_orden_mesero> doc_pedidos_orden_mesero { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cat_clientes> cat_clientes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<doc_empleados_productos_descuentos> doc_empleados_productos_descuentos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<doc_ventas> doc_ventas { get; set; }
    }
}
