//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConexionBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class sis_bitacora_general
    {
        public int BitacoraId { get; set; }
        public Nullable<int> SucursalId { get; set; }
        public string Detalle { get; set; }
        public System.DateTime CreadoEl { get; set; }
        public Nullable<int> CreadoPor { get; set; }
    
        public virtual cat_sucursales cat_sucursales { get; set; }
        public virtual cat_sucursales cat_sucursales1 { get; set; }
    }
}
