//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConexionBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class sis_usuarios_roles
    {
        public int UsuarioId { get; set; }
        public short RolId { get; set; }
        public System.DateTime CreadoEl { get; set; }
    
        public virtual cat_usuarios cat_usuarios { get; set; }
        public virtual sis_roles sis_roles { get; set; }
    }
}
