//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConexionBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class sis_preferencias_sucursales
    {
        public int Id { get; set; }
        public int SucursalId { get; set; }
        public int PreferenciaId { get; set; }
        public string Valor { get; set; }
        public Nullable<System.DateTime> CreadoEl { get; set; }
    
        public virtual cat_sucursales cat_sucursales { get; set; }
        public virtual sis_preferencias sis_preferencias { get; set; }
    }
}
