//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConexionBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class sis_versiones_detalle
    {
        public int VersionDetalleId { get; set; }
        public short VersionId { get; set; }
        public string ScriptName { get; set; }
        public bool Completado { get; set; }
    
        public virtual sis_versiones sis_versiones { get; set; }
    }
}
