//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConexionBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class sis_cuenta
    {
        public int EmpresaId { get; set; }
        public string ClienteKey { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string URLValidacion { get; set; }
        public Nullable<int> ClaveSucursal { get; set; }
    
        public virtual cat_empresas cat_empresas { get; set; }
    }
}
