//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConexionBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class sis_perfiles_menu
    {
        public short PerfilId { get; set; }
        public short MenuId { get; set; }
        public System.DateTime CreadoEl { get; set; }
    
        public virtual sis_perfiles sis_perfiles { get; set; }
        public virtual sis_menu sis_menu { get; set; }
    }
}
