//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConexionBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class sis_preferencias_sucursales
    {
        public int Id { get; set; }
        public int SucursalId { get; set; }
        public int PreferenciaId { get; set; }
        public string Valor { get; set; }
        public Nullable<System.DateTime> CreadoEl { get; set; }
    
        public virtual cat_sucursales cat_sucursales { get; set; }
        public virtual sis_preferencias sis_preferencias { get; set; }
    }
}
