//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConexionBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class sis_menu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sis_menu()
        {
            this.sis_menu1 = new HashSet<sis_menu>();
            this.sis_perfiles_menu = new HashSet<sis_perfiles_menu>();
        }
    
        public short MenuId { get; set; }
        public string Titulo { get; set; }
        public string Descripcion { get; set; }
        public byte Tipo { get; set; }
        public string MenuWinBarNameId { get; set; }
        public Nullable<short> MenuPadreId { get; set; }
        public bool Activo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sis_menu> sis_menu1 { get; set; }
        public virtual sis_menu sis_menu2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sis_perfiles_menu> sis_perfiles_menu { get; set; }
    }
}
