//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConexionBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class sis_cuenta
    {
        public int EmpresaId { get; set; }
        public string ClienteKey { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string URLValidacion { get; set; }
        public Nullable<int> ClaveSucursal { get; set; }
        public Nullable<bool> TieneRec { get; set; }
        public Nullable<decimal> PorcRec { get; set; }
    
        public virtual cat_empresas cat_empresas { get; set; }
    }
}
